### ISSUE TITLE
Plymouth support?

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/anarchy-linux#110]
https://wiki.archlinux.org/index.php/plymouth

Is it possible to get Plymouth support enabled out of the box as an option? This *may* have issues when using the Nvidia proprietary driver + KMS, not sure. I've never been able to successfully enable Plymouth support even after following all instructions to the letter (I'd get a Nvidia logo at boot, not the splash I wanted).

Thoughts? I'm a bit iffy about suggesting this one since it's only on AUR, but it *could* be added to the AA repo itself too. Plus there's the needed hook, adding quiet splash to the kernel command line, disabling the display manager and replacing with the right Plymouth one for a smooth transition, gdm-plymouth for GDM users, etc.

**Comment by deadhead420** [comment]
I have considered this but it will be a bit of a pain to impliment

**Comment by the57200** [comment]
Is it implemented ?

**Comment by BooBerry** [comment]
Nope, doesn't look like it. *If* it's going to be implemented, it may take some time.

**Comment by deadhead420** [comment]
Considering the extensive configuration high chance for bugs and the fact that it might not even work on some peoples systems, and it is AUR only, its unlikely to be included any time soon.

**Comment by BooBerry** [comment]
Honestly? I completely agree with you. I tried a couple days ago setting up Plymouth and it still didn't even work for me no matter what I did. So yeah, it's probably just a waste of time, IMO.
