### ISSUE TITLE
Translation tool questions

### ISSUE THREAD

**Issue by notramo** [deadhead420/anarchy-linux#324]
I asked them about if they were accept the project.
There are lot of outdated translation strings, that are hard to find, and translatewiki.net can find them, and mark as outdated.
If the project was on translatewiki.net, more people could help translating, because experience in git is not needed in that case.

**Comment by deadhead420** [comment]
Thats a great idea. I will have to look into it when I have some time. Feel free to submit the translations to them if you're able. 

Thanks

**Comment by notramo** [comment]
Translatewiki supports [these](https://www.mediawiki.org/wiki/Help:Extension:Translate/File_format_support#Supported_file_formats) translation file formats. Custom formats can be added if someone has PHP skills, but I think using one of the currently supported formats is easier.
What do you think about using YAML for translations, and writing a program that generates sourceable output for the shell from the YAML file? The current translations are key-based, and YAML is also a key-based format.

**Comment by notramo** [comment]
As talked in #446, I will create a translation tool.
I want to implement ability to add comments to strings to help translators. I also want to implement marking of translations e.g. partially translated, or equivocal.
This could be done with commented lines in the shell translation file, but I think it looks bad, it is more difficult to implement, and there are more corner cases.
The other solution would be using YAML for storing values, translations, and comments, and a program would generate shell sourceable output at ISO build.  YAML is easy to read for humans, and it is easy to parse for programs. It looks better, and there are less corner cases.
What do you think, @condor2, @deadhead420, @pnedkov?

**Comment by deadhead420** [comment]
Sounds great. The translations have been a bit of a mess for awhile now.

**Comment by notramo** [comment]
But what solution should we use? I prefer YAML.

**Comment by Ricardo-Simoes** [comment]
Is there any chance you might consider online translation platforms like https://weblate.org , https://crowdin.com/ or https://www.transifex.com/ (my personal favorite) ? PLEASE, PLEASE, PLEASE?

**Comment by notramo** [comment]
Using online translation tools is efficient only when there are more translators for each language.
And they also use YAML or gettext files.

**Comment by deadhead420** [comment]
I would love to do something to fix up the translations but don't have a whole lot of time to mess with them. I'm too focused on testing new features and getting the next release ready. Feel free to pitch out some ideas and I'll let you know if I want to go forward with it. Whatever will be easiest for everyone is best, I don't really have the time to touch the translations at all but I do agree that something needs to be done because its a huge pain in the ass for me to add new lines to every single translation.

**Comment by notramo** [comment]
@deadhead420, I will create the translation tool next week. I will handle the translation problem.
But the question is still that should I use YAML, or source comments?
If there will be more translators for each language, we might use a web translation platform when we use YAML. (I prefer translatewiki.net, because it is not commercial)

**Comment by deadhead420** [comment]
@notramo whatever you think would be best. I started developing a shell tool to manage the translations awhile back but gave up on it. I just need to be able to keep track of everything and keep it all organized and I want to have the same lines in each translation without needing to manually add them to each one.

**Comment by notramo** [comment]
Ok, @deadhead420 I will use YAML, because it is more powerful, and looks better than shell.

**Comment by deadhead420** [comment]
Sounds good to me. Just let me know if you need anything

**Comment by JustMeErazem** [comment]
@notramo Are you still interested in trying to set up the translation system?

**Comment by JustMeErazem** [comment]
Closing this for now, since there doesn't seem to be any interest. Will reopen an issue later about using weblate for Anarchy.
