### ISSUE TITLE
What kind of keyboard layout do you use for your password?

### ISSUE THREAD

**Issue by remussatala** [deadhead420/anarchy-linux#349]
I need my password to be recognized.
I also use such characters in the password:
!@#$%^&*()_+

Please do some checks by typing such characters in the user password and HDD encryption password.

**Comment by pnedkov** [comment]
What is the problem?!

**Comment by remussatala** [comment]
I do not know what a problem I have. Maybe I'm crazy. Maybe I should go to a doctor. :)

**Comment by remussatala** [comment]
This password can not be used: !@#$%^&*()_+
I need to be able to use a password with these characters: !@#$%^&*()_+

**Comment by condor2** [comment]
Tested today a password for LVM encryption: !@#$test
I boot up and I checked to see if really use special characters so I typed 1234test, and password wrong. Then: !@#$test, password good and arch boot up.

Tested with english language. In what language you have tested?

**Comment by remussatala** [comment]
I tested in English and Romanian and did not work. It did not work on logging or encrypted volume.

**Comment by condor2** [comment]
Hmm..

What ISO version you have used? Update script before by pressing 2 then Enter.

**Comment by Jakhe** [comment]
Hi.  
I configure the passphrase for lvm encryption during installation in azerty but during the boot the keyboard is configured as qwerty.

**Comment by JustMeErazem** [comment]
Closing in favor of #579 (more info about the bug there).
