### ISSUE TITLE
Feature request for direct UEFI

### ISSUE THREAD

**Issue by Prezto** [deadhead420/anarchy-linux#378]
I have installed with Arch-anywhere and i am wondering of direct UEFI would be an option to implement. Now i have modified the installation to use direct UEFI, but it would be nice to have support for it in the installer.

https://wiki.archlinux.org/index.php/EFISTUB

**Comment by condor2** [comment]
EFISTUB was added by @ftes 

https://github.com/deadhead420/arch-linux-anywhere/pull/357

**Comment by ftes** [comment]
If you are correctly booting with UEFI, you should see a boot loader option _EFISTUB_ (underneath Grub, SysLinux and Systemd).

Make sure to _update_ the arch anywhere (option 2 after booting).
