### ISSUE TITLE
Pamac 6.0.1 is released and needs new depends.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#432]
Hello. As Pamac 6.0 is out, you'll need to add archlinux-appstream-data.

https://github.com/manjaro/pamac/releases/tag/v6.0.1

**Comment by Bundy01** [comment]
Salut,
il est désormais dans le dépot 'extra' depuis le 30 sept.

**Comment by tommyshem** [comment]
I think he means in arch-anywhere repo the pamac-aur package is at version 5.1.1 and new release  version of pamac is version 6.0.3. I think he is asking for the package to be updated. I have used AUR instead of the arch-anywhere repo package to update my system.
