### ISSUE TITLE
Xfce4 Goodies

### ISSUE THREAD

**Issue by Firminator** [deadhead420/anarchy-linux#435]
It's unclear for users what packages will be installed when selecting Xfce4 Goodies. Possible to add this information to the menu?
Thanks a lot.

**Comment by lawrencedark** [comment]
I would think exploring http://goodies.xfce.org/ would be enough without adding all that info to the menu, but that's just me. 😉

**Comment by Firminator** [comment]
You shouldn't need a second computer and internet access to decide if you need to install Xfce Goodies or not. The package info in the menu should have the info available for users.
