### ISSUE TITLE
Repo arch-anywhere down ?

### ISSUE THREAD

**Issue by Bundy01** [deadhead420/anarchy-linux#437]
Hi,
**http://arch-anywhere.org/repo/** whith error  '403 Forbiden'
Is there a new repo ?
Thanks.

**Comment by condor2** [comment]
https://arch-anywhere.org/packages/

**Comment by Bundy01** [comment]
hi,
Condor2, with pacman -Syyu : The requested URL returned error: 404

**Comment by condor2** [comment]
Need to test :)

**Comment by condor2** [comment]
Should work
