### ISSUE TITLE
Audio/Video codec

### ISSUE THREAD

**Issue by aaaaadrien** [deadhead420/anarchy-linux#444]
Hi,
Is it possible to add in Multimedia category the possibility to install all codecs ? (gst-plugins-{good,bad,ugly})

Thanks

**Comment by condor2** [comment]
You have already in Multimedia.....Multimedia codecs
`gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly ffmpegthumbnailer gst-libav`

**Comment by deadhead420** [comment]
As mentioned by @condor2  this is already a feature
