### ISSUE TITLE
Gui-installer-script : conflict between rfkill and util-linux

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#455]
Both packages are conflicting while script is processing... See attached screenshot.

![capture du 2017-10-25 11-22-19](https://user-images.githubusercontent.com/8571419/31991145-55144e38-b977-11e7-87bb-76a6403993b9.png)

Sorry for the french speaking text, but I think translation is useless here.

**Comment by condor2** [comment]
I don`t tink GUI creator is ready.

**Comment by FredBezies** [comment]
At all. There are other bugs I saw. If you want I report them, I'll do this with pleasure :)

**Comment by FredBezies** [comment]
Looks like disabling testing from host OS fixes this bug :(
