### ISSUE TITLE
CLI-installer-script : cannot run installer or updater...

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#456]
Just made an iso from an up-to-date github clone. I cannot run cli-installer... Just look at screenshot :(

![virtualbox_anarchy 1 0_25_10_2017_11_27_11](https://user-images.githubusercontent.com/8571419/31991274-a8f63610-b977-11e7-91e2-471469e37336.png)

**Comment by condor2** [comment]
What write in the picture?

Select an option.....or type **anarchy** to install :)

**Comment by FredBezies** [comment]
Or simply modify this two lines in https://github.com/deadhead420/anarchy-linux/blob/master/extra/.zshrc

alias 1="arch-anywhere"
alias 2="arch-anywhere -u"

by 

alias 1="anarchy"
alias 2="anarchy -u"

Simple guess, of course. Must be tested :D

**Comment by FredBezies** [comment]
Even if updater part is broken, at least, I can launch installer by entering one.

**Comment by condor2** [comment]
I have changed the lines.

**Comment by FredBezies** [comment]
Thanks!
