### ISSUE TITLE
Laptop detection is "blocking" language files display.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#457]
Last bug for now. Language files are not loaded. Using an ISO I made with a fresh github clone, I noticed that languages files are not loaded anymore by installer script. Every single language I chose leads to this: 

![virtualbox_anarchy 1 0_25_10_2017_11_33_06](https://user-images.githubusercontent.com/8571419/31991535-4acc09f6-b978-11e7-9b88-eb4835a18ccc.png)

**Comment by condor2** [comment]
Comment out these lines from anarchy-installer
`		if "$LAPTOP" ; then
			/usr/bin/dialog --colors --backtitle "$backtitle $(acpi)" --title "$op_title" "$@"
		fi`

Laptop detection need to be fixed :)

**Comment by FredBezies** [comment]
You nailed it. Laptop detection is WIP. Modifying bug title.

**Comment by condor2** [comment]
Disabled for moment laptop detection, because need the acpi package to be installed :)

**Comment by deadhead420** [comment]
fixed
