### ISSUE TITLE
Updater script is broken.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#458]
After fixing bug  #456 by modifying .zshrc, I noticed updater part is kinda broken... A lot of Arch-Anywhere references... I know, it is a WIP! 

![virtualbox_anarchy 1 0_25_10_2017_12_06_41](https://user-images.githubusercontent.com/8571419/31993432-64cf897c-b97d-11e7-8316-d64ebd4a6c4e.png)

**Comment by FredBezies** [comment]
Seems to be related to anarchy.conf file, line 124 to 129:

```
cp $tmp_dir/arch-linux-anywhere-master/anarchy-installer.sh /usr/bin/anarchy
cp $tmp_dir/arch-linux-anywhere-master/etc/anarchy.conf /etc/anarchy.conf
cp $tmp_dir/arch-linux-anywhere-master/lib/* /usr/lib/anarchy/
cp $tmp_dir/arch-linux-anywhere-master/lang/* /usr/share/anarchy/lang/
cp -f $tmp_dir/arch-linux-anywhere-master/extra/{sysinfo,iptest} /usr/bin/
cp -r $tmp_dir/arch-linux-anywhere-master/extra/* /usr/share/anarchy/extra/
```
Looks like they must be modified, or am I wrong?

**Comment by condor2** [comment]
Fixed
