### ISSUE TITLE
Some categories are missing in package selection.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#462]
Noticed while translating for french locale. Missing parts : programming, system and database as far as I can see.

Any idea on how to fix that? Thanks!

![virtualbox_anarchy 1 0_25_10_2017_14_31_34](https://user-images.githubusercontent.com/8571419/31999269-fbfa0a24-b992-11e7-8cb0-30b8b484ada6.png)

**Comment by condor2** [comment]
Add from here in you language
https://github.com/deadhead420/anarchy-linux/blob/master/etc/anarchy.conf

**Comment by FredBezies** [comment]
Oops. But I noticed a small bug. Right after text_editor_msg, instead of having util and util_msg lines, I got system and system_msg. Only for french translation of for every single one remaining?

**Comment by condor2** [comment]
English file was changed. I will recheck all languages...when i have some time ....

**Comment by FredBezies** [comment]
Will do it for french. Update is coming with some synchronization.

**Comment by notramo** [comment]
What about doing string synchronization with a special tool, or a web translation system? It could also track if a string's English value is changed.
I opened #446 and #324 because of this.
I recommend creating a custom tool for this, because most web translation systems doesn't support this kind of files.

**Comment by FredBezies** [comment]
And it will help a lot translator life too :)

By the way, testing last modifications in order to have something really eye-pretty :D

**Comment by deadhead420** [comment]
This still a bug?

**Comment by FredBezies** [comment]
Made changes for french translation. Can't say for other ones.

**Comment by deadhead420** [comment]
As long as its working in english I'm alright lol. If its broken in other languages that will just give more translators a reason to come fix it ;)

**Comment by FredBezies** [comment]
And at least warn them: hey, as new ISO is coming out, you're needed to upgrade your translations. Thanks! :)
