### ISSUE TITLE
[Anarchy repo] Pamac-aur needs to be upgraded.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#463]
Looking at repository page, I noticed pamac-aur was still in version 6.0.3... Last one is 6.2.0 (upstream) and 6.1.2 on AUR.

So a little update is needed I think. By the way, Pamac 6.1.0+ is using meson and ninja for building.

**Comment by condor2** [comment]
Updated all packages.

**Comment by FredBezies** [comment]
Thanks.
