### ISSUE TITLE
[GUI-creator] you need to install numix-icon-theme-git for numix-icon-circle build

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#466]
In line 152 of gui-creator script, you need to replace makepkg -s by makepkg -si in order to build numix-icon-circle.

It is the place where numix-icon-base is generated.

**Comment by deadhead420** [comment]
Cool thanks for pointing that out.

**Comment by FredBezies** [comment]
You're welcome. Fixed in new script I see. Will try this new one asap.
