### ISSUE TITLE
Creator script : is arc-master removing line obsolete?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#468]
In unified creator script, you can read this in line 230: 

`sudo cp -r /tmp/arc-openbox-master/{Arc,Arc-Dark,Arc-Darker} "$customiso"/arch/"$sys"/squashfs-root/usr/share/anarchy/extra/desktop`

Openbox doesn't seem to be provided. What about removing this line?

**Comment by deadhead420** [comment]
done
