### ISSUE TITLE
NVIDIA video driver doesn't install when selected through GUI install process

### ISSUE THREAD

**Issue by cjmccormick** [deadhead420/anarchy-linux#469]
I ran into this issue again after a clean install recently. I had run the install process again and manually select the nouveau driver as default then I swapped out nouveau for nvidia after successful complete install. A few months back I had this same issue. Just wondering what seems to be the issue. I posted about this on the Arch Anywhere Facebook group.

**Comment by pnedkov** [comment]
The proprietary nvidia driver is not supposed to be installed if you go the nouveau route.

**Comment by cjmccormick** [comment]
Yes, that is correct. I tried to install nvidia driver first, but when the installer was getting ready to install everything to hdd it failed, so I restarted the install process and manually selected nouveau so it would install all the way

**Comment by pnedkov** [comment]
Installation log? Version? Did you update the installer? If "yes" when?

**Comment by cjmccormick** [comment]
No log, its the most up to date .iso from website. No didn't update the installer. I have a Nvidia Strix 1060. I'll have to try to do it in VM and see if I can reproduce it again.

**Comment by cjmccormick** [comment]
In the mean time here are the installs that happen back in March of this year. I tried installing 5 times https://www.facebook.com/groups/archanywhere/permalink/1776256962702475/

**Comment by cjmccormick** [comment]
Hmm, unable to test the install as VirtualBox installs don't prompt for GPU install, so I don't get any errors.

**Comment by tenten8401** [comment]
Just did an install with a GTX 1070 and selected nvidia at install. Installed everything just fine, I did update the installer.

Enabling the DRM module had some problems for SDDM and KDE though, so I reinstalled with that off and again the driver seemed to install just fine.

**Comment by cjmccormick** [comment]
There was a stand alone GDM bug after the last update within last few days from Arch repos. But that is something entirely different. I will see if I can reproduce it in VM, I haven't had luck yet.

**Comment by pnedkov** [comment]
@cjmccormick 
> No didn't update the installer.

And here lies the problem. You should always run the current version of the installer before reporting a bug. Otherwise it may not be relevant. When I installed my workstation with P2000 I used this version: 3f06474bfbb0b4f77e63ecd331d6fcae8aa6dfc8. After that I don't know if everything will wok as well as before simply because the project took in new direction and I have not played with the latest changes yet. I have nvidia + DRM + KDE + SDDM on my system and everything works flawlessly.

You will not be able to test it with VirtualBox because NVIDIA shows up in the menu only if nvidia video card has been detected.

**Comment by cjmccormick** [comment]
Updating the installer through the live cd doesn't work, even after updating the mirrors I tried that a few times last night

**Comment by cjmccormick** [comment]
Alright, did a complete install like I would normally i3 as a WM, SDDM, few apps. Now it is hanging on boot for me. I read somewhere it's a bug with GDM/Nvidia. Also was unable to update installer before running the installer.

**Comment by cjmccormick** [comment]
![Unable to update installer](https://user-images.githubusercontent.com/1686880/32255667-4aa17346-be80-11e7-9e0e-e36547119e6c.jpg)

**Comment by cjmccormick** [comment]
![Hang at boot after clean full install](https://user-images.githubusercontent.com/1686880/32255677-5b398a36-be80-11e7-8973-5f2ec427f084.jpg)

**Comment by cjmccormick** [comment]
I am able to startx by opening up a new shell alt + f2

**Comment by pnedkov** [comment]
It looks like the transition from Arch Anywhere **installer** to Anarchy Linux **distribution** is far from smooth. If you want to chase and report new bugs you are welcome. But if you want to just quickly install your system I would suggest:

1. Boot from Arch Anywhere 2.2.9 iso with `cow_spacesize=1G`
https://github.com/deadhead420/anarchy-linux/issues/246#issuecomment-289197782
2. Install git
pacman -Sy
pacman -S git 
3. git clone https://github.com/deadhead420/anarchy-linux.git
5. cd anarchy-linux
6. git checkout 3f06474
7. ./arch-installer.sh

**Comment by cjmccormick** [comment]
Thanks, I tried doing that earlier, but also had some errors making the iso. I just ran the 2.2.9 iso again and did complete install with no apps. Booted into command line and updated arch and installed  everything I needed. seems to be working so far :dancer:

**Comment by deadhead420** [comment]
Still an issue?

**Comment by JustMeErazem** [comment]
It appears this is not an issue anymore, so I'm closing it. Reopen if needed.
