### ISSUE TITLE
Request: Add SwayWM & Wayland support.

### ISSUE THREAD

**Issue by SkiMaskTheSlumpGod** [deadhead420/anarchy-linux#472]
# Requesting support for SwayWM & Wayland.

![image](https://user-images.githubusercontent.com/33149862/32097358-8b1ebfac-bb09-11e7-9519-e4b4d3008256.png) 

[SwayWM](http://swaywm.org/) | [Arch Wiki](https://wiki.archlinux.org/index.php/Sway)

> Sway is tiling Wayland compositor and a drop-in replacement for the i3 window manager for X11. It works with your existing i3 configuration and supports most of i3's features, plus a few extras.

> We also maintain the wlroots project to provide a modular basis for Sway and other Wayland compositors to build upon, and we publish standards for interopable Wayland desktops.

![image](https://user-images.githubusercontent.com/33149862/32097366-913e95b0-bb09-11e7-9f97-58e34cb04ca1.png)

[Wayland](https://wayland.freedesktop.org/) | [Arch Wiki](https://wiki.archlinux.org/index.php/wayland)

> Wayland is intended as a simpler replacement for X, easier to develop and maintain. GNOME and KDE are expected to be ported to it.

> Wayland is a protocol for a compositor to talk to its clients as well as a C library implementation of that protocol. The compositor can be a standalone display server running on Linux kernel modesetting and evdev input devices, an X application, or a wayland client itself. The clients can be traditional applications, X servers (rootless or fullscreen) or other display servers.

> Part of the Wayland project is also the Weston reference implementation of a Wayland compositor. Weston can run as an X client or under Linux KMS and ships with a few demo clients. The Weston compositor is a minimal and fast compositor and is suitable for many embedded and mobile use cases.

**Comment by notramo** [comment]
There is already an issue for it, #90.
I think, most Wayland DEs are currently experimental, and if someone uses SWAY, he can install pure Arch.

**Comment by SkiMaskTheSlumpGod** [comment]
Ah, I'm sorry. 
Hadn't noticed that issue.
And yes I could install pure Arch and then install it, but adding it in a later state would make it easier than doing it manually. I'm just as lazy like 99% of the users of this project. 👍

**Comment by deadhead420** [comment]
Is sway in the official arch repos?

**Comment by SkiMaskTheSlumpGod** [comment]
Yes it is sir.
[Official](https://www.archlinux.org/packages/?name=sway) | [AUR (Git)](https://aur.archlinux.org/packages/sway-git/)

**Comment by deadhead420** [comment]
I've added sway but configuration will be up to the user. I made it so when you select sway it copies over the default config from /etc/sway/config

**Comment by notramo** [comment]
I would add a default Anarchy themed config (a cool color theme and a wallpaper).
