### ISSUE TITLE
Anarchy repository cannot be added :(

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#473]
I noticed that when I'm using installer on GUI ISO, I cannot enable and add anarchy repository. I asked for pacaur and pamac-aur.

I got this answer: 

![virtualbox_anarchy 0 9_27_10_2017_11_46_53](https://user-images.githubusercontent.com/8571419/32098465-17ef4642-bb0d-11e7-858b-45ef3c0d9280.png)

Rough translation: 

Number of packages: 5
Download size: 0

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/commit/5932f477a808a08ba501425ced50b73f99740252

**Comment by FredBezies** [comment]
And verified :)

Thanks.
