### ISSUE TITLE
GUI ISO : logout icon is not working.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#474]
Just click on it, and you'll get an oblogout not found error :(

![virtualbox_anarchy linux 0 9_27_10_2017_12_38_41](https://user-images.githubusercontent.com/8571419/32100406-e9e82a3c-bb13-11e7-9546-c8f4357b1344.png)

Using 0.9.0 release git commit base for ISO building.

**Comment by deadhead420** [comment]
Will fix it soon

**Comment by deadhead420** [comment]
A few things wrong here. No icons on the desktop.

**Comment by condor2** [comment]
Added oblogout package, should work now :)

**Comment by FredBezies** [comment]
Indeed. A good bug is a dead bug :)
