### ISSUE TITLE
Cannot install Anarchy OpenBox Edition : some packages are missing.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#475]
I tried to install Anarchy OpenBox Edition and it failed. Looking at /tmp/anarchy.log, I noticed it failed while trying to grab opensnap.

See attached screenshot.

![virtualbox_anarchy linux 0 9_27_10_2017_12_45_46](https://user-images.githubusercontent.com/8571419/32100629-c719b3ee-bb14-11e7-9b7e-e0962a98d4c8.png)

**Comment by deadhead420** [comment]
I know. I haven't worked on it yet... Will be fixed soon

**Comment by FredBezies** [comment]
You can add lightdm-settings and lightdm-slick-greeter.

![virtualbox_anarchy 0 9_27_10_2017_17_23_38](https://user-images.githubusercontent.com/8571419/32111762-c09900d4-bb3b-11e7-94ea-53d6ddc3962c.png)

Modifying bug title.

**Comment by deadhead420** [comment]
fixed. I had a naming issue with the local repo and the anarchy repo. Renamed and all should be good now.

**Comment by FredBezies** [comment]
Good, but there is no oblogout installation done. Will open a new bug.
