### ISSUE TITLE
No ISO Downloading.

### ISSUE THREAD

**Issue by WhispersOfJ** [deadhead420/anarchy-linux#482]
While I am sure this will be fixed, just a heads up.

`> ./anarchy-creator.sh -c
Checking for updated ISO...

No archiso found under /home/user/Git/anarchy-linux
Would you like to download now? [y/N]: y
--2017-10-27 11:26:30--  http://mirrors.kernel.org/archlinux/iso/2017.10.01/
Resolving mirrors.kernel.org... 149.20.37.36, 2001:4f8:4:6f:0:1994:3:14
Connecting to mirrors.kernel.org|149.20.37.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                            [ <=>                                                                                                        ]   1.14K  --.-KB/s    in 0s      

2017-10-27 11:26:30 (52.7 MB/s) - ‘index.html’ saved [1170]`

**Comment by condor2** [comment]
A temporary fix :)
https://github.com/deadhead420/anarchy-linux/commit/6ae75758b1efcd676c3eaec58efa4671adf562b5
