### ISSUE TITLE
[Wish] Getting PulseAudio activated by default on live ISO.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#485]
Hello. Noticed a small bug. When I boot GUI ISO, PulseAudio mixer is muted by default. VirtualBox bug?

**Comment by deadhead420** [comment]
That's default behavior.

**Comment by FredBezies** [comment]
So it is not a bug. Changing title to express a wish so.

**Comment by deadhead420** [comment]
Not a bug, however for some reason I have no idea how to make it unmuted by default on the ISO. I have tried, I can look into it a bit more but it seems that default behaivor for pulseauido is to be muted.

**Comment by deadhead420** [comment]
Might have a fix. Testing.

**Comment by FredBezies** [comment]
Keeping fingers crossed :)

Weird that PulseAudio output is muted on start... :(

Besides this, it is a great pleasure to beta-test Anarchy live ISO :)

**Comment by deadhead420** [comment]
I appreciate the help. Takes a lot of the load off of me.

**Comment by FredBezies** [comment]
I understand. A friend of mine is doing a lot of Manjaro respins and it takes a lot of time :(

**Comment by deadhead420** [comment]
Fixed. I had to add the package alsa-utils

**Comment by FredBezies** [comment]
Ouch. Will test this asap...
