### ISSUE TITLE
Anarchy OpenBox Edition : logout not enabled as oblogout is not installed.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#486]
A little but annoying bug. I installed Anarchy OpenBox Edition and I noticed there is no logout icon working in fresh installation.

I could install oblogout after reboot on new installation.

![capture du 2017-10-28 10-24-00](https://user-images.githubusercontent.com/8571419/32132783-2703ea58-bbca-11e7-98a7-f84bc92e5dbe.png)

See attached screenshot. Logout icon is grayed and not working.

**Comment by DraGiuS** [comment]
Check the human icon at the right in the front panel, then you can log out.

**Comment by FredBezies** [comment]
I thought it was accessibility options. Will try again asap today.

**Comment by deadhead420** [comment]
I'll fix it soon. As I said I'm too busy working on other stuff to worry about openbox at the moment.

**Comment by FredBezies** [comment]
OK. I wanted to report this issue. At least, this bug will act as a reminder. Have a good day.

**Comment by FredBezies** [comment]
Will try this asap. Just wait for util-linux / rfkill conflict to be fixed.

See https://bugs.archlinux.org/task/56173 and https://bugs.archlinux.org/task/56171

**Comment by FredBezies** [comment]
Luckily, I had a remaining CLI ISO, so I installed openbox with it after upgrading the installer. Logout is working. Empty icons ? Well, I said "no" when installer asked me if I want AA xfce extras.

![virtualbox_anarchy_31_10_2017_08_31_30](https://user-images.githubusercontent.com/8571419/32212219-3bec46ec-be16-11e7-866c-e341f1923387.png)
