### ISSUE TITLE
ZSH Issue

### ISSUE THREAD

**Issue by WhispersOfJ** [deadhead420/anarchy-linux#489]
`source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh`

This is not found at the beginning of the cli installer.

**Comment by condor2** [comment]
Test now
https://github.com/deadhead420/anarchy-linux/commit/64f6e4c0949e93e504073c66c6f963c2351150d7

**Comment by WhispersOfJ** [comment]
No joy.

Same error.

**Comment by deadhead420** [comment]
fixed
