### ISSUE TITLE
Adding a new user is not possible in last installation screen.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#492]
I noticed that you cannot add a new user using the related option in last installation screen, where you can enter a chroot or reboot your freshly installed system.

When I try add a new user, I saw installer working on my root and user password... Adding new user dialog was skipped.

Related to user management added recently?

**Comment by condor2** [comment]
Possible a missing variable or incorrect in you language

**Comment by FredBezies** [comment]
Indeed. Fixing the typo right now.

**Comment by FredBezies** [comment]
Nothing really changed. I got when I select add a new user:

1. passwd root
2. useradd "already existing user"
3. passwd "already existing user"

Something is broken :(

**Comment by condor2** [comment]
1000000000 Euro to fix the bug =))
PS. Checking now )

**Comment by FredBezies** [comment]
I confess my bug title was not clear :(

**Comment by deadhead420** [comment]
Please don't mess with it. I'll fix

**Comment by deadhead420** [comment]
Fixed. @FredBezies thanks for the reminder.

**Comment by FredBezies** [comment]
Thanks for the fix. I just verified it. And you're welcome for the reminder.
