### ISSUE TITLE
Ending Errors

### ISSUE THREAD

**Issue by WhispersOfJ** [deadhead420/anarchy-linux#501]
```
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
Failed to enable unit, unit NetworkManager.service does not exist.
rm: cannot remove '/home/worshipper/Git/anarchy/customiso/arch/x86_64/squashfs-root/boot/initramfs-linux-fallback.img': No such file or directory
mv: cannot stat '/home/worshipper/Git/anarchy/customiso/arch/x86_64/squashfs-root/boot/vmlinuz-linux': No such file or directory
mv: cannot stat '/home/worshipper/Git/anarchy/customiso/arch/x86_64/squashfs-root/boot/initramfs-linux.img': No such file or directory
rm: cannot remove '/home/worshipper/Git/anarchy/customiso/arch/x86_64/squashfs-root/root/install.txt': No such file or directory
zsh:1: command not found: xdg-user-dirs-update
cp: target '/home/worshipper/Git/anarchy/customiso/arch/x86_64/squashfs-root/home/user/Desktop' is not a directory
```

**Comment by deadhead420** [comment]
???????

**Comment by deadhead420** [comment]
Not an issue?

**Comment by WhispersOfJ** [comment]
Vague title yes, but I couldn't think of another thing to title it.

Those are literally the last lines before it starts to make the ISO

**Comment by deadhead420** [comment]
You might be doing something wrong. Works for me. Unless someone made a change last night and created a bug.

**Comment by deadhead420** [comment]
I'll test when I get home but it should work. You have archiso?

**Comment by WhispersOfJ** [comment]
i do, I will run it again, maybe it was a weird one off.

**Comment by WhispersOfJ** [comment]
Just call me an idiot, apparently I didn't have archiso installed after running `pacman -Qi`

**Comment by deadhead420** [comment]
Dont need to install archiso. The archiso needs to be in the anarchy directory.

**Comment by WhispersOfJ** [comment]
Sorry, my brain is a little late to the party. I had the latest arch ISO in the Dir and apparently I hit the wrong keys last night because now all is well.
