### ISSUE TITLE
Can't install lightdm

### ISSUE THREAD

**Issue by DraGiuS** [deadhead420/anarchy-linux#502]
Lightdm-settings and lightdm-sleek-greeter are not found, so the installer crashes at this time.

**Comment by deadhead420** [comment]
You need to re-create the iso

**Comment by DraGiuS** [comment]
Not closed, Lightdm-settings still not found.

**Comment by deadhead420** [comment]
.... Yes it is. As I said you need to recreate the ISO. This isn't a bug

**Comment by DraGiuS** [comment]
I you said i've recreated a iso, but the bug is still here

**Comment by deadhead420** [comment]
rm -rf /tmp/*

Then try again. Works for me. You might not have everything configured
right.
