### ISSUE TITLE
Non-Minimal feels too bloated

### ISSUE THREAD

**Issue by tenten8401** [deadhead420/anarchy-linux#503]
As the title says, I personally think the default option of a "non-minimal" KDE Plasma installation just feels _waaay_ too bloated. I don't feel like a lot of the applications installed would even be used, and would just take up bandwidth and disk space. Some good examples of what I'm talking about is anything in the Education or Games category in the menu. Maybe replace Konquerer with something like QupZilla as well.

I could see how it could be useful for some things, so I'm not completely suggesting removal, but maybe an inbetween of some sorts, reccomended install maybe?

Just my personal opinion on the matter. I'd be 95% happy with minimal, but there's no GTK theme included for Breeze & Breeze Dark, No option to change it in system settings, and no option to configure SDDM.

Edit: Just wanted to include a list of the ones I feel are unneccesary incase no one feels like doing a fresh install: (Education) KWordQuiz, KHangMan, Kiten, KLettres, Kanagram, Parley, KBruch, KAlgebra, Kig, KmPlot, KAlgebra Mobile, Rocs, Artikulate, KTurtle, KGeorgraphy, Step, Blinken, Minuet, KTouch, KStars, Kalzium, KDE Marble, (Games) KSnakeDuel, Bomber, Kollision, KBounce, Grantier, KBreakOut, KBlocks, KGoldrunner, Kolf, Kapman, KSpaceDuel, KBlackBox, KSquares, Bovo, KFourInLine, Kigo, Kajongg, KMahjongg, KReversi, Shisen-Sho, Kinki, LSkat, KPatience, KHangMan, Kanagram, Blinken, Potato Guy, Kubrick, Palpeli, Picmi, KSudoku, KDiamond, Klikety, SameGame, Konquest, KMines, KNetWalk, Naval Battle, Ksirk Skin Editor, KAtomic, Killbots, Kolor Lines, KJumpingCube and KsirK.

Not to bash the programs or anything, but I just feel like 99% of users wouldn't get any use whatsoever out of the majority of those apps.

**Comment by cjmccormick** [comment]
Well, it is non-minimal like you say. KDE is pretty bloated even if you take those games away imo

**Comment by deadhead420** [comment]
I agree KDE is a bloated pos... This isn't really an issue with the installer but rather with kde/plasma...

**Comment by deadhead420** [comment]
The non-minimal comes with all that by default, this is the reason I offered a minimal option.

**Comment by deadhead420** [comment]
I'll look into it more but I prefer to stay far away from kde. Honestly I've only installed it once.

**Comment by tenten8401** [comment]
Just occured to me every single one of those apps is in the `kdeedu` and `kdegames` group... Possibly install without those?

**Comment by tenten8401** [comment]
Just wanted to throw this out here: https://github.com/Antergos/Cnchi/blob/202443c52232cb8b80a8621230da11657d9b959f/data/packages.xml#L373
Pretty decent combination of packages, would

**Comment by spsf64** [comment]
Why not rename it to "Kde full install"?
