### ISSUE TITLE
[Anarchy OpenBox Edition] GUI Authentication tool is missing

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#507]
After installing Anarchy OpenBox from an ISO based on a november 1st git clone, I noticed lxession is missing. I added Pamac-aur to my installation, and I cannot access to options which needs privilege escalation, like adding package.

I searched for lxession. It was missing.

**Comment by notramo** [comment]
I use Pamac on ArchLinux with i3, and `lxsession` isn’t installed, only `lxpolkit`.

**Comment by deadhead420** [comment]
Lxsession isn't included with i3?

**Comment by deadhead420** [comment]
Not sure what is up with all the lxsession complaints... Someone asked the
same about i3. Lxsession isn't included with open box or i3. Install lxde
if you want lx sessions.....

**Comment by FredBezies** [comment]
I explain myself bad. There is no authentication dialog box when needed.

Modifying title.

**Comment by FredBezies** [comment]
A screenshot to show what is happening. Dialog box can be translated as "Authentication failed".

![capture du 2017-11-01 15-57-47](https://user-images.githubusercontent.com/8571419/32280946-aae61386-bf1d-11e7-9f86-80e512d30ae4.png)

**Comment by FredBezies** [comment]
In order to get an authentication dialog, I used this workaround:

1. adding lxsession
2. put it in .config/openbox/autostart with lxpolkit & at the end
3. logged out and logged in

**Comment by deadhead420** [comment]
Not really an anarchy bug.

**Comment by FredBezies** [comment]
OK. Closing it so.

**Comment by deadhead420** [comment]
I don't want to include lxsession if I don't have to... The bug is with
what? Pacaur?

**Comment by notramo** [comment]
There is no graphical polkit authentication agent.
If `lxsession` isn't included in some profiles, it shouldn't offer to install Pamac, because it will be unusable.

**Comment by FredBezies** [comment]
I think every single software which needs temporary root rights will need it. I didn't want to start such a war here. Some people would appreciate to get a GUI package manager and an authentication tool to make it work better.

That's all I meant. Let's stop there, OK? I made a wrong move opening this bug, I admit it. Let's go to real bugs. I'm sorry. OK?

**Comment by deadhead420** [comment]
I can install it if the user selects pamac but don't want to include it
with anything by default.

On Nov 1, 2017 12:54 PM, "FredBezies" <notifications@github.com> wrote:

I think every single software which needs temporary root rights will need
it. I didn't want to start such a war here. Some people would appreciate to
get a GUI package manager and an authentication tool to make it work better.

That's all I meant. Let's stop there, OK? I made a wrong move opening this
bug, I admit it. Let's go to real bugs. I'm sorry. OK?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/deadhead420/anarchy-linux/issues/507#issuecomment-341167349>,
or mute the thread

**Comment by deadhead420** [comment]
But what about other desktops. Xfce4, etc... I find it very unnecessary to
install lxsession anywhere other than lxde.

**Comment by notramo** [comment]
Other desktops have own authentication agents.
https://wiki.archlinux.org/index.php/Polkit#Authentication_agents

**Comment by FredBezies** [comment]
@deadhead420 you could do so for pamac-aur. But I was just noticing that authentication was missing. That's it.

@notramo indeed. I was just telling an authentication agent in GUI mode could help for some tools... I didn't want _to start a war_ :(

Well, subject is closed now?

**Comment by deadhead420** [comment]
I'll work on it in the next release. For now it will just have to be up to the user.

**Comment by deadhead420** [comment]
I will add it for openbox.

**Comment by deadhead420** [comment]
added polkit-gnome to openbox
