### ISSUE TITLE
Lightdm don't open session.

### ISSUE THREAD

**Issue by DraGiuS** [deadhead420/anarchy-linux#510]
When i wanted to login with lightdm, i can't.
![1509561504901-1749754731](https://user-images.githubusercontent.com/26351654/32291117-663a0f02-bf3c-11e7-9137-b0cd146a2e03.jpg)

And lightdm doesn't list more than one session
I've installed openbox,xmonad and sway.

![1509561409147-831007352](https://user-images.githubusercontent.com/26351654/32291012-1ac31956-bf3c-11e7-9954-3c9053c6a56e.jpg)
Sorry for these shitty screenshot.

**Comment by deadhead420** [comment]
Working on a fix
