### ISSUE TITLE
Declared configuration

### ISSUE THREAD

**Issue by faddat** [deadhead420/anarchy-linux#52]
Ever used nixos?

I think it would be fantastic to set up some sort of an auto install that nukes my hard disk and outs arch in place the same way I always do, since I am a frequent OS exploder.

**Comment by deadhead420** [comment]
I've thought about this... You mean like a preconfigured install. Pretty much just push go and it installs arch just the way you want it... I thought of a way to do this. The first time the user does the install normally & all selected options are saved in a file. Then at the end of the install the that file is copied to the new system & can be used for a future install without the need for any user input at all.

**Comment by faddat** [comment]
Let me mature the concept somewhat, I've been cooking it in my head a
bit... Ever installed nixos?

Works more or less as I was describing.  Kinda thinking tho what if AUA
asked you to login to GitHub when it started up the first time and gave the
user a repo, AUA.  In faddat/AUA, we would find:

-Package list for pacman and repo list for any third party repos
-AUR package list
-non-secret .files

I've been calling the repo the "distribution state".  Whole thing seems
eminently achievable even for someone with my very limited code-fu.  This
here message on your repo is mostly to get you thoughts on the path of
least resistance re: implementing all this.

As an aside.... Omg don't you love what's going on with kernel 4.x?   Very
exciting times to be geeky!
