### ISSUE TITLE
[GUI ISO] Changing keyboard in installer is not taken into account.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#522]
I noticed when you're using anarchy installer with the GUI ISO, keyboard changes are not taken into account.

I wanted a french keyboard layout to enter root password and user name. I noticed it was still using an english US layout. Annoying.

Of course, keyboard layout changes are taken into account in CLI ISO.

I had to enter setxkbmap followed by keyboard code in a terminal to get all the time the right layout.

**Comment by deadhead420** [comment]
Should be fixed now

**Comment by FredBezies** [comment]
Indeed. Trying to install Anarchy Budgie Edition within the GUI for another bug and it works. Thanks for the fix!
