### ISSUE TITLE
As there is no .png wallpaper files, why copying them?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#526]
In /lib/configure_desktop.sh, line 403, you can read this: 

`cp -r "$aa_dir"/extra/wallpapers/{*.jpeg,*.png} "$ARCH"/usr/share/backgrounds/anarchy/`

Are there is no wallpapers in png format, why keeping *.png?

**Comment by deadhead420** [comment]
Png can be removed

**Comment by FredBezies** [comment]
Ok.

**Comment by deadhead420** [comment]
Feel free to pull request otherwise I'll fix it later
