### ISSUE TITLE
mono-addins

### ISSUE THREAD

**Issue by WhispersOfJ** [deadhead420/anarchy-linux#528]
Playing with various configurations in the VM this morning, I was installing Pinta from the software list and...

```
error: mono-addins: key "Daniel Isenmann <daniel@archlinux.org>" is disabled
:: File /var/cache/pacman/pkg/mono-addins-1.1-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by FredBezies** [comment]
Looks like archlinux-keyring is not up-to-date.

**Comment by WhispersOfJ** [comment]
Absolutely the case.

Even after making sure it was updated in a non-VM, the package will not install for the moment.

**Comment by pnedkov** [comment]
I got this on two of my systems with Arch Linux running for years. Not a Arch Anywhere/Anarchy bug.

**Comment by condor2** [comment]
You need to download mono-addins-1.1-1-x86_64.pkg.tar.xz then:
`sudo pacman -U mono-addins-1.1-1-x86_64.pkg.tar.xz`
`sudo pacman -S pinta`

**Comment by AM-SL** [comment]
@condor2
Worked , but how can we update keyring ?
I know the commands for this , I means fix the pacman installing not manually installing with -U option.
Just waiting fix this prob ?

**Comment by deadhead420** [comment]
This should be fixed?
