### ISSUE TITLE
Anarchy Xfce and OpenBox Edition are not loaded after login.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#529]
Using ISO made based on this git commit - https://github.com/deadhead420/anarchy-linux/commit/be58a7fd7ae1d198282400c309110dd3c130b7fb - I noticed Anarchy based versions are not loaded after login using lightdm.

I can't say for Gnome, Cinnamon and Budgie custom ones, but for Xfce and OpenBox are loaded using their default settings.

I don't think there is any commit fixing that annoying behaviour.

Annoying.

**Comment by deadhead420** [comment]
Noticed this last night but had to go to sleep. I'll fix it

**Comment by FredBezies** [comment]
Ok. Will wait for your fix so.

**Comment by condor2** [comment]
Test now
https://github.com/deadhead420/anarchy-linux/commit/6925e55d6bc72de5f46f533ff360372c2547b271

**Comment by FredBezies** [comment]
@condor2 ISO generated. Testing them right now. Will report within one or two hours from now.

**Comment by FredBezies** [comment]
First part of my test of anarchy flavour installation:

1. Xfce is OK besides wallpaper is missing. Fix proposed to modify extra/desktop/xfce4/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
2. OpenBox is OK too.

Will test Gnome, Cinnamon and Budgie and report.

**Comment by deadhead420** [comment]
@FredBezies thanks man. Appreciate the help. I'm at work right now but will be doing some work on it when I get home.

**Comment by FredBezies** [comment]
Well, I'm a beta-tester in my soul and arch-anywhere helped me at least twice... So, helping Anarchy Linux is "mandatory" :)

I have time for me. Will report for others flavors. Let's keep fingers crossed.

**Comment by FredBezies** [comment]
Ok for Gnome, Cinnamon and Budgie but with some little bugs I'll report.
