### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by faddat** [deadhead420/anarchy-linux#53]
Hey so in the past couple of years I've done a lot of work with the Linux kernel for arm and generally making Linux work happily on arm CPUs. I think that it wouldn't be so difficult to make an arch anywhere disk Image Maker that would make disk images than for example are writable onto SD cards for use in devices like the Raspberry Pi or orange pi. Generally, I think that this would kick ass and make Arch Linux anywhere even worse than it already does. Let me tell you the usual route of doing this basically from an x86 machine you would chroot into an arm rootfs mounted via loopback, install all necessary packages, put u-boot at that magical sector zero and then flash the SD card with the image.  

I am having some difficulty with making the image work right.  If you'd like to compare notes,i bet we can add a whole new galaxy of hw support to your creation here.

**Comment by deadhead420** [comment]
Love the idea! Im all for getting this working.

**Comment by faddat** [comment]
@deadhead420 
I'd like to map this out with you.  Can we set up a time to talk?

**Comment by deadhead420** [comment]
For sure! Do you have a prefered way to chat?

**Comment by deadhead420** [comment]
@faddat Would still be cool to see this but don't have enough time to mess with it at the moment unless someone else wants to give it a go.

**Comment by Thijzer** [comment]
Hmm, would it not be easier to chroot a minimal arm image or something and start working from chroot? If that is possible?

**Comment by ljoli** [comment]
Yeah it's not easy but it's possible. 
look => https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot
After that you need to choice your platform and cross-compile : 
https://archlinuxarm.org/wiki/Distcc_Cross-Compiling

**Comment by Thijzer** [comment]
Nice source, thanks. Maybe that should be enough for the first steps.  I think a preprovision/chef way of reducing the setup drag might also help to build these images.

**Comment by JustMeErazem** [comment]
@Thijzer The [Arch Linux ARM](https://archlinuxarm.org/) project might be a good start. The scripts can be adapted to use that ISO if needed.

**Comment by JustMeErazem** [comment]
Closing since there doesn't seem to be any interest in this. Reopen if needed.
