### ISSUE TITLE
[Anarchy Budgie] no wallpaper for both lightdm and environment.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#533]
I tested Anarchy Budgie and noticed I have no wallpaper in Budgie, only a big white background. It hurts a little :(

In full screen, I got a black background.

![virtualbox_anarchy linux 0 9 - budgie_03_11_2017_14_57_31](https://user-images.githubusercontent.com/8571419/32377272-5d1960e6-c0a7-11e7-99f6-a1e184a90488.png)

For lightdm, no star background, only a black one.

**Comment by condor2** [comment]
No wallpapers because as this config, budgie install not create backgrounds folder.

**Comment by FredBezies** [comment]
Sorry for late testing... I was kinda away from my keyboard.

Will report asap!
