### ISSUE TITLE
[Anarchy Budgie] Please add Gnome Control Center to tweak settings.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#534]
As Budgie is working with gnome tools, you need them to have a working environment. Without them, Budgie is an empty shell :(

**Comment by FredBezies** [comment]
As bug #533 is fixed, I think you need to add at least gnome-control-center to offer settings configuration. Budgie Desktop configuration panel is not really powerfull here.

Modifying title.

**Comment by condor2** [comment]
Added gnome-control-center

**Comment by FredBezies** [comment]
Fixed :)
