### ISSUE TITLE
VBoxClient listed twice if Anarchy is installed in VirtualBox

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#535]
Noticed this small bug in ./config/openbox/autostart. If you install Anarchy OpenBox in VirtualBox, vboxclient line is listed twice.

Not a big bad bug, but a small and annoying one.

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/commit/48b92588814563a1113000849a4375d81a282b19

**Comment by FredBezies** [comment]
Fixed. Another bug bites the dust :)
