### ISSUE TITLE
Pamac-aur signing key obsolete or incorrect ?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#539]
I noticed I cannot install pamac-aur from anarchy repository: every single time, I got an error message like this.

![virtualbox_anarchy budgie v1_07_11_2017_09_04_00](https://user-images.githubusercontent.com/8571419/32483059-9fd5a0a2-c39a-11e7-9deb-df27610fa093.png)

I tried with sublime-text from anarchy repository and it worked flawlessly. Any idea?

**Comment by condor2** [comment]
I think I forgot to update anarchy.db :)

**Comment by FredBezies** [comment]
Fixed. Adding pamac-aur into a new install from scratch works flawlessly.
