### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by ljoli** [deadhead420/anarchy-linux#541]
Hello,

I have the following configuration (pc laptop ) :  MSI GL62 7RD-280XFR
- cpu : Intel Core i5-7300HQ 
- GPU : NVIDIA GeForce GTX 1050

When I run anarchy, I have a blue screen.
So, my laptop is block on this stage.

**Comment by condor2** [comment]
Blue screen??
Post a picture.

**Comment by ljoli** [comment]
![20171108_001058](https://user-images.githubusercontent.com/5774664/32613535-77e5356c-c56b-11e7-895e-a702e3192c63.jpg)

the blue screen ...

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/issues/344
