### ISSUE TITLE
Can't add Anarchy's ISO to MultiSystem

### ISSUE THREAD

**Issue by filisko** [deadhead420/anarchy-linux#543]
Hi,
When I try to add newest available ISO to MultiSystem (https://sourceforge.net/projects/multisystem/) I get an error message.
I can add any other GNU/Linux distribution except this one, what makes it that special the ISO image?

**Comment by condor2** [comment]
What error message.....?

**Comment by filisko** [comment]
It says something like 'At the moment this ISO is not supported' (i've go it in spanish).

**Comment by WhispersOfJ** [comment]
So, what I think, is that MultiSystem needs to be informed of this.

**Comment by JustMeErazem** [comment]
@filisko Multisystem needs to support AnarchyLinux, not the other way around. Try informing them so they can add support for it, and please close the issue.
