### ISSUE TITLE
Some programs are not installed using default Xfce Anarchy

### ISSUE THREAD

**Issue by spsf64** [deadhead420/anarchy-linux#545]
I created I new cli ISO from git and installed the default anarchy xfce
Noticed that icons are created on panel but the programs were not installed: clementine, gimp and vlc.
Chromium and Libreoffice are working and were pulled automatically...
See attached image:

![aa-xfce](https://user-images.githubusercontent.com/1877391/32746960-6ad7deb6-c89e-11e7-9dca-6b16f5757cc4.png)

**Comment by FredBezies** [comment]
Indeed. Looks like $extra is not working correctly in configure_desktop.sh :(

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/commit/828e7fe4e344245a6a3c46957c88e83fbf3bb681
