### ISSUE TITLE
Are Desktop Extras deactivated ?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#546]
Kind of followup for bug #545. I noticed I was not asked if I want desktop extras to be added when I install a blank environment.

Known bug?

**Comment by WhispersOfJ** [comment]
Come to think about it, I wasn't asked either....

**Comment by condor2** [comment]
Extras are xfce4-goodies :)

https://github.com/deadhead420/anarchy-linux/commit/828e7fe4e344245a6a3c46957c88e83fbf3bb681

**Comment by FredBezies** [comment]
So closing this bug. No needs to let it opened!
