### ISSUE TITLE
Broken network check

### ISSUE THREAD

**Issue by raspi** [deadhead420/anarchy-linux#549]
If I try to choose specific mirror I get an error that network is not available. If I just go with default everything works.

I traced the error to broken SSL certificate in the mirror updating script.

    if [ "$code" == "$default" ]; then
					curl -s "$mirror_url" | sed '10,1000d;s/#//' >/etc/pacman.d/mirrorlist.bak &
				else
					curl -s "$mirror_url" >/etc/pacman.d/mirrorlist.bak &
				fi

**Comment by deadhead420** [comment]
Fixed by adding -k option to curl command
