### ISSUE TITLE
Chinese character show ■■■■

### ISSUE THREAD

**Issue by spphinslove** [deadhead420/anarchy-linux#550]
I uncomment zh_CN.UTF.8 UTF-8 in the locale.gen and change language.sh
![2017-11-30 17-39-06](https://user-images.githubusercontent.com/11383988/33424122-c9f71038-d5f5-11e7-8294-01ccdd160cad.png)
![2017-11-30 17-52-33](https://user-images.githubusercontent.com/11383988/33424620-4f2f9cb0-d5f7-11e7-9590-5a10acc9e96e.png)

![2017-11-30 17-51-04](https://user-images.githubusercontent.com/11383988/33424569-307eb9d6-d5f7-11e7-9f75-a31bd590ad32.png)

**Comment by condor2** [comment]
Chines will work only in GUI installer.

**Comment by spphinslove** [comment]
@condor2  never for CUI？

**Comment by condor2** [comment]
No.

**Comment by spphinslove** [comment]
@condor2 why？the linux kernel dosen't support Chinese character？

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/issues/45
