### ISSUE TITLE
[SOLVED] Frozen blue screen on XPS 15 before install

### ISSUE THREAD

**Issue by AlanMarrec** [deadhead420/anarchy-linux#551]
Hi ! :)

I downloaded the ISO on the official website, made my USB key with dd and installed Arch on my first laptop (Lenovo something, old one aha) and I wanted to do the same thing on my new XPS 15.
I can boot on the key, I have the "start" screen, wired connection ok, update and download french mirror.
Then I press "1" to start the installation and nothing, it's freeze on a blue screen :(

In my BIOS I just disabled Secure Boot, but I tried to boot in Legacy mode, same thing.

Do you have a solution ? :)

Thanks in advance ! :)

Maki

**Comment by AlanMarrec** [comment]
So, I edit my BIOS settings 

Disabled secure boot 
Put the ssd into ahci mode instead of raid 
Set fastboot as Thorough 

And here is a screenshot :
https://img15.hostingpics.net/pics/819191435802613271804.jpg

**Comment by ljoli** [comment]
I had the same mistake => #541 
So, I find one solution according to my graphic card.

You need to disable the **nouveau** driver
=> https://wiki.archlinux.org/index.php/nouveau

**Comment by ljoli** [comment]
The system may start if the Nouveau driver is disabled by passing the following kernel parameters: 
`modprobe.blacklist=nouveau`

**Comment by AlanMarrec** [comment]
Hey Ijoli ! 
Thanks for your answer, but how do you do that ? I blacklisted the nouveau driver like this : 

> /etc/modprobe.d/nouveau.conf
`blacklist nouveau
blacklist lbm-nouveau
options nouveau modeset=0
alias nouveau off
alias lbm-nouveau off`

**Comment by ljoli** [comment]
Hello,
I create an iso of Anarchy.
And when I boot, I change with "TAB" key the option of kernel and add modprobe.blacklist=nouveau.

So, after that boot normally

**Comment by AlanMarrec** [comment]
Hey ! 
Thanks for helping me, it worked ! 

But I have a second problem now.. I tried to install lightDM and Deepin and perfs are very bad.. 
Slow system, mouse frozen and Slow / frozen keyboard. 
What did you installed as graphic driver during installation ? And which graphic environnement are you using ?

**Comment by AlanMarrec** [comment]
Hey !
Finally I installed manually Arch Linux ^^
I follow this link : http://www.saminiir.com/installing-arch-linux-on-dell-xps-15/

It works really nice now :D 

Maybe add nvidia drivers in Arch-anywhere installation ?
