### ISSUE TITLE
Install fails on pacaur

### ISSUE THREAD

**Issue by ehussong** [deadhead420/anarchy-linux#552]
downloading pacaur-4.7.10-1-any.any.pkg.tar.xz. . .
checking keyring. . . 
error: key "EEEEE2EEEE2EEEEE" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packes to new root
2017-12-07 00:34: Install failed: please report to developer
arch-anywhere  12.05s user 16.68s system 7% cpu 6:40.33 total

**Comment by condor2** [comment]
Arch Anywhere 2.2.9?

**Comment by ehussong** [comment]
Correct. Although I've heard of some issues with pacaur and it being abandoned over the last few days so I suspect it may be unrelated to Arch Anywhere.

Thanks for what you do!
