### ISSUE TITLE
As a followup of bug #554, remove pacaur references from all languages?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#557]
In bug #554, I talked about pacaur removing from anarchy repository as it is now unmaintained. I remove it from french translation, what about other ones?

https://github.com/deadhead420/anarchy-linux/commit/e6373e8f34f1ae0f40757fce664600352873dff5 -> pacaur removing from script.

https://github.com/deadhead420/anarchy-linux/commit/c4ea2221b14b6d6864f7ffd3398621211449adac -> pacaur translation line removed.

**Comment by condor2** [comment]
The others one read from anarchy.conf, but pacaur was removed.

**Comment by FredBezies** [comment]
OK. So closing this bug.
