### ISSUE TITLE
Pacaur and Yaourt can't be downloaded in the cli and stop the installation 

### ISSUE THREAD

**Issue by Nanodragon999** [deadhead420/anarchy-linux#560]
When and if you install pacaur and/or yaourt,they won't download for some reason,(though all the other package does download without problem,the keys and signature are working too) and they stop the installation script to continue.
Of course,if neither pacaur or/and yaourt are checked to be downloaded,there no error that i'm aware of.And tested after the reboot to download them,and it does indeed work,but not in the cli as stated.(they respectively cause this,which mean i tried one at a time then both multiple times)

regard,N.

EDIT: just seen on reddit and github that pacaur isn't maintained anymore :/ maybe that's related,though,i'm no expert and i don't always follow the news there.

**Comment by condor2** [comment]
Arch Anywhere 2.2.9? or you made anarchy iso?

**Comment by FredBezies** [comment]
As pacaur was removed, it seems to be that bugreporter used arch-anywhere 2.2.9 ISO.

**Comment by deadhead420** [comment]
Pacaur was removed and yaourt seems to be working fine.
