### ISSUE TITLE
On first add user step, you can use uppercase letters

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#562]
Notice this bug recently. It seems there is no uppercase check on this step. It could lead to uppercase login name which is not a good thing.

Can it be possible to add a detection in this step? Anybody can make a mistake here.

**Comment by deadhead420** [comment]
i'll check but if I'm not mistaken it automatically converts any upercase letters into lowercase

**Comment by deadhead420** [comment]
Fixed
