### ISSUE TITLE
openjdk8 cannot be installed

### ISSUE THREAD

**Issue by lagout** [deadhead420/anarchy-linux#564]
Hello.

While testing your installer, I noticed that OpenJDK8 cannot be installed. I had to add I was stressing your installer.

It looks like references for openJDK8 packages are not right. Please look at attached screenshot.

Thanks.

![capture d ecran_2018-01-02_17-54-49](https://user-images.githubusercontent.com/7132184/34492948-ee5cd6de-efe9-11e7-8906-708b492dd227.png)

**Comment by deadhead420** [comment]
Fixed, thanks for reporting
