### ISSUE TITLE
Warning when installing icon packages in creation script

### ISSUE THREAD

**Issue by lagout** [deadhead420/anarchy-linux#565]
Hello.

I was generating a GUI ISO image when I noticed that there is a small warning related to an invalid icon cache.

There were no graphical issues in my test in a virtual machine after this. See attached screenshot to get more details.

![capture d ecran_2018-01-02_17-31-15](https://user-images.githubusercontent.com/7132184/34493043-60911422-efea-11e7-9416-814621719d9a.png)

Thanks.

**Comment by deadhead420** [comment]
This can be safely ignored.
