### ISSUE TITLE
Errors when creating CLI ISO

### ISSUE THREAD

**Issue by spsf64** [deadhead420/anarchy-linux#566]
I got the errors below when running "./anarchy-creator.sh -c" with latest commits as of today jan/03/2018 (UTC)
Am I doing something wrong?
TIA

warning: could not get file information for boot/vmlinuz-linux
==> ERROR: /proc must be mounted!

:: Retrieving packages...
 linux-4.14.10-1-x86_64    59.9 MiB  19.9M/s 00:03 [----------------------] 100%
(1/1) checking keys in keyring                     [----------------------] 100%
(1/1) checking package integrity                   [----------------------] 100%
(1/1) loading package files                        [----------------------] 100%
(1/1) checking for file conflicts                  [----------------------] 100%
(1/1) checking available disk space                [----------------------] 100%
warning: could not get file information for boot/vmlinuz-linux
:: Processing package changes...
(1/1) upgrading linux                              [----------------------] 100%
:: Running post-transaction hooks...
(1/3) Updating linux module dependencies...
(2/3) Updating linux initcpios...
==> ERROR: /proc must be mounted!
error: command failed to execute correctly
(3/3) Arming ConditionNeedsUpdate...

**Comment by deadhead420** [comment]
fixed
