### ISSUE TITLE
GUI ISO : installer menu display is broken

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#569]
Hello. I generated an ISO based on this commit : https://github.com/deadhead420/anarchy-linux/commit/c2c175a0b0f6f5836cee5ee78f0f15280203c89c

When I launched installer, I saw an horrible garbage... Just look attached screenshot... Any idea? Thanks.

![virtualbox_anarchy cinnamon_04_01_2018_20_32_14](https://user-images.githubusercontent.com/8571419/34580835-ab6b0110-f18e-11e7-82d3-bde967957355.png)

**Comment by FredBezies** [comment]
Looks like any caracter who are not pure ASCII are not displayed. Why?

**Comment by deadhead420** [comment]
Not sure about this one... Its working fine for me.

**Comment by FredBezies** [comment]
Of course, CLI ISO is OK...

![virtualbox_anarchy budgie_04_01_2018_21_15_10](https://user-images.githubusercontent.com/8571419/34582532-69a409ba-f194-11e7-9400-cd108a6f195e.png)

I'm testing something. As I wanted to get an english speaking ISO in every single corner of the GUI), I entered export LANG=C before launching script on my fr_FR.UTF-8 localized installation... Will report soon.

**Comment by FredBezies** [comment]
Well, even without modifying LANG, I still have this bug :(

Very weird. Will investigate more tomorrow morning.

**Comment by FredBezies** [comment]
Long dead bug. Closing it.
