### ISSUE TITLE
mouse and keyboard issue

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#574]
It looks pretty awesome so far, but for some reason it will not let me use any of my mice or keyboards.

I am running a 2012 Hewelet Packard. AMD chipset. 64bit. Not sure if that info helps any, I've never made linux build, so I don't know what it needs.

Also at boot, it says: 
[Failed] Failed to start load kernel modules
[Failed] Failed to start Apply kernel modules

It says that twice before the desktop environment is up. I'm guessing the mouse and keyboard are kernel modules.

**Comment by nastybuttler322** [comment]
Just to clarify, I'm talking about the desktop version. Nothing failed during the boot of the CLI iso, and my keyboards work fine with the CLI version too. It might have something to do with the I/O code you worked on about 9 or 10 hours ago, but idk because I think that had something to do with squashfs.

**Comment by spsf64** [comment]
I have same problem when I boot into UEFI mode.
If I boot into BIOS mode it works fine
My mobo is Gigabyte, inxi report:

Machine:   Device: desktop System: Gigabyte product: Z87-D3HP serial: N/A
           Mobo: Gigabyte model: Z87-D3HP-CF v: x.x serial: N/A
           BIOS: American Megatrends v: F7 date: 08/12/2014
CPU:       Quad core Intel Core i7-4770 (-MT-MCP-) cache: 8192 KB
           clock speeds: max: 3900 MHz 1: 3392 MHz 2: 3392 MHz 3: 3392 MHz
           4: 3392 MHz 5: 3392 MHz 6: 3392 MHz 7: 3392 MHz 8: 3392 MHz

**Comment by gmcclins** [comment]
@nastybuttler322, Is this the same message? I get this when I try to install the desktop version during ISO boot. Ultimately install fails. #576. I also had no problem with the CLI image.

 Are you saying you were able to install using that ISO but on first boot your having these issues?

![1 bootup](https://user-images.githubusercontent.com/1461924/34618956-78a31f9e-f20e-11e7-9b83-279265efc401.PNG)

**Comment by nastybuttler322** [comment]
@gmcclins Yeah, that's the same message. 

"Are you saying you were able to install using that ISO": 
Desktop version = no
CLI version = no

" but on first boot your having these issues?":
 The issues with the mouse and keyboard only  apply to the desktop iso. The messages in your picture only apply to the desktop version.

The new CLI version is having a different issue that I'm about to post.

**Comment by nastybuttler322** [comment]
Sorry, I just read that image more carefully. The messages say "modules." I rebooted my PC a few times as I wrote the post, so that I could type the things that fail exactly as it says when the image boots.

When the desktop environment starts, it looks real cool. I can see a mouse pointer. But I can't move the courser, and I can't do anything with my keyboard.

I'm pretty sure that the modules that fail during the GUI boot are needed for the mouse and keyboard inputs.

**Comment by nastybuttler322** [comment]
@spsf64 Yep, just reloaded the image to my USB and tried it in Legacy. Everything seems to work fine now! Thanks man.

**Comment by asdkant** [comment]
Doesn't this mean that UEFI boot on the graphical live CD is not working? That's a problem for people who use nvidia and want a full-resolution console (as per https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting , unless I'm missing something)

I had this issue too, my motherboard is a Gigabyte AX370-Gaming K7 and I'm using a Geforce gtx1050ti graphics card

**Comment by brumle80** [comment]
This is still an issue with UEFI install using gui installer...

Booting legacy is not a fix.

So still not fixed and impossible to troubleshoot as no keyboard or mouse/touchpad works.

**Comment by felipehespanhol** [comment]
Same issue herre!

**Comment by psposito** [comment]
I have experienced the same last night...

**Comment by dim1tri** [comment]
Same issue. MB: Gigabyte Z370N

**Comment by scjeti** [comment]
Same issue, please fix this issue !

**Comment by msal4** [comment]
Same issue

**Comment by condor2** [comment]
Similar bug from that image was here...
https://github.com/systemd/systemd/issues/7838

**Comment by adri326** [comment]
Same issue on a late 2016 27'' mac, none of the keyboard nor mice were working, replugging them changed nothing

**Comment by cjmccormick** [comment]
This is still a issue I just tried doing a fresh install and Im am getting the same results. I get the same errors as stated above and unable to use mouse and keyboard.

**Comment by bbbenji** [comment]
Same issue on T40s.

**Comment by Histamine** [comment]
same issue with my laptop.
booting in UEFI with the gui mod => no keyboard neither mouse. 

please fix it!

**Comment by daef** [comment]
this issue is closed, maybe someone of the plagued should open a new issue :)
