### ISSUE TITLE
No official Bangladesh Mirror found in the script.

### ISSUE THREAD

**Issue by Neil-seu** [deadhead420/anarchy-linux#578]
It would be great if you kindly add the Bangladesh mirror. 

N.B: For Bangladesh, code is BD. 
![20d8e218-a195-4ea1-b249-37b53de7f01c](https://user-images.githubusercontent.com/24956423/34621192-5b702444-f272-11e7-8313-4ac3bf781dcf.png)

**Comment by condor2** [comment]
Added
