### ISSUE TITLE
Suggest : Depreciated french translation for touchpad & not installing usefull drivers

### ISSUE THREAD

**Issue by AntoninCamus** [deadhead420/anarchy-linux#582]
```
On advanced install, the installer offer to install xf86-input-synaptics package. As said on official page : https://wiki.archlinux.org/index.php/Touchpad_Synaptics

Warning: xf86-input-synaptics is no longer actively updated. If possible, use libinput.

My touchpad for example is not supported (multitouch and gestures) without libinput even with synaptics. 
```

[Edit] Apparently, I reinstalled and it's libinput which is installed. Maybe an error of translation in french ?

And for keyboard issues, again in advance installation, installer don't offer an "driver" category, and the installer don't install `xf86-input-mouse` nor `xf86-input-keyboard` automatically (which is surprising).

**Comment by FredBezies** [comment]
Thanks for the info. Fixed wrong translation. See this pull request: https://github.com/deadhead420/anarchy-linux/pull/588

**Comment by FredBezies** [comment]
@AntoninCamus please try again with a CLI iso and an update before installation. It will be better :)

**Comment by AntoninCamus** [comment]
Ok, I'll try tomorrow then. It's exactly the message I saw, and now the translation is closer of initial english.

PS : I don't understand why not precising which driver it is installing, saying for example "Voulez-vous installer le pilote xf86-input-libinput pour le touchpad ? [...]" (in french as in english).
