### ISSUE TITLE
UEFI boot problem

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#586]
This issue was on a Hewlet Packard make, 2012 Pavilion model, 64bit AMD chipset, 8GB ram. I do not know if that information helps, or is needed because I do not know enough about operating systems yet.

Booting in UEFI mode, the boot process reports:

[Failed] Failed to start load kernel modules
[Failed] Failed to start Apply kernel modules

It says that twice before the desktop environment is up. I'm guessing the mouse and keyboard are kernel modules, because none of my mice and keyboards work when I boot the iso in UEFI mode.

Also, the grey option page that lets me select 'Restart, Run memtest, boot Anarchy, etc." did not run. 

spfs64 pointed out to me that this did not happen for him when he did not boot the iso in UEFI mode. I just booted it in Legacy mode, and everything appears to work just fine. There were no fail messages during Legacy boot.

I closed the mouse and keyboard issue, and opened this one in it's place. It seemed like it might be easier to narrow the source of the problem down by pointing out that it's only for UEFI mode.

AWESOME desktop theme btw!

**Comment by deadhead420** [comment]
I have the same issue on my computer when booting UEFI mode... As far as I can tell this is an apic / arch issue I was able to resolve this by adding: "noapic pci=assign-busses apicmaintimer idle=poll reboot=cold,hard" to the kernel command line of the bootloader.

**Comment by includes08** [comment]
All i get to lately is the login screen and past that no desktop just the Anarchy background.

**Comment by includes08** [comment]
i thought i had the same error but i don't nvm :( i'm clueless now. I tried the first one and cinnamon both nothing yet.

**Comment by nastybuttler322** [comment]
@deadhead420 Makes sense, freeBSD has a similar problem with acpi.

**Comment by nastybuttler322** [comment]
@includes08 do you get failed messages at the initial boot?

**Comment by nastybuttler322** [comment]
@includes08  Did you type startx after you logged in?

**Comment by nastybuttler322** [comment]
I'm closing this since it sounds like a kernel issue, and not one that is related to the installer.
