### ISSUE TITLE
Anarchy creator script: cannot build needed packages. Error in line 154.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#591]
With last modifications in anarchy-creator.sh script, ISO creation failed really soon. My building host: archlinux with a cleaned up /tmp repertory.

Here is the log I get:

```
fred@fredo-arch ~/anarchy-linux (git)-[master] % ./anarchy-creator.sh -a
Checking for updated ISO...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
fetchmirrors/
fetchmirrors/.SRCINFO
fetchmirrors/PKGBUILD
./anarchy-creator.sh: line 154: cd: fetchmirrors: No such file or directory
```

Line 154:

`cd $pkg || exit`

I found a dirty workaround... I added /tmp/ before pkg and packages are being built. Looks like your if condition is not met :(

**Comment by deadhead420** [comment]
Sorry about that I forgot to upload the fix. Your workaround was not ditry at all but correct lol. Was just a small typo bug.

**Comment by FredBezies** [comment]
OK. But I found my workaround to be kinda quick and dirty!
