### ISSUE TITLE
VMware open-vm-tools recent changes

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/anarchy-linux#592]
I've tested this several times in VMs and worked it out.

Anarchy correctly installs open-vm-tools (and gtkmm) to get Anarchy working as a guest in VMware, however due to recent changes there's still a couple steps still needed to get everything working (e.g. automatic window resizing);

https://wiki.archlinux.org/index.php/VMware/Installing_Arch_as_a_guest

For example as of the first of the year, enabling and starting **vmtoolsd.service** is required now, regardless if you're using **multi-user** or **graphical** targets.

> NOTE: as of 2018/01/01 it appears that vmtoolsd (as described in above multi-user section) must also be enabled in order for this to work properly.

Prerequisite:

**cat /proc/version > /etc/arch-release** needs to be ran as root (if it isn't already done, haven't checked).

First, vmtoolsd.service needs to be enabled and started now:

```
systemctl enable vmtoolsd.service
systemctl start vmtoolsd.service
```

If you're also using graphical target (which we probably are):

```
systemctl enable vmware-vmblock-fuse.service
systemctl start vmware-vmblock-fuse.service
```

That *should* be it to get everything working again out-of-the-box with Anarchy VMware guests.

Thoughts?

**Comment by BooBerry** [comment]
Furthermore, why does the installer enable a VirtualBox service while installing in VMware? I noticed that go by near the end of the install.

**Comment by nastybuttler322** [comment]
I'm confused, are you saying that I have to do that stuff to run a VM within Arch, or to run Arch within a VM? I ask because I was having some difficulty with running a VM ,it was telling me to enable virtualization in the BIOS that definitely has that enabled. I'm not trying to clog the github up by seeking help with my issue, I'm just trying to figure out if what you're talking about is relevant to my issue.

**Comment by BooBerry** [comment]
Anarchy (Arch) as a guest, so within a VM in this context.

**Comment by deadhead420** [comment]
Thanks for the repot @BooBerry vmtoolsd will now be enabled when using vmware. Also the reason for that message is because I forgot to change it when copying from the line I used for vbox lol, I've also updated it to show enabling vmtoolsd.service
