### ISSUE TITLE
Add KDE applications as an option

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/anarchy-linux#593]
Self-explanatory, should be an option ONLY if you've selected KDE Plasma as your desktop environment and want the 'full' Plasma experience. It could be a choice prompted if you decide not to do the minimal Plasma install (e.g. Do you want to install the KDE Applications group?).

If this is not doable, at the very least add Kate (text editor) to the **Text Editors** software install list (if selected KDE Plasma) and Konsole to Terminal software install list (if selected KDE Plasma).

**Comment by BooBerry** [comment]
Looks like it already does this if you don't select the minimal install.

My apologies. Closed!

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/issues/503
