### ISSUE TITLE
Failed to install packages to new root

### ISSUE THREAD

**Issue by BooBerry** [deadhead420/anarchy-linux#598]
Getting this in my test VM when trying to install Anarchy with the latest GUI and CLI ISOs from the main site (and the CLI ISO built from the latest commits). I'm installing only base + base-devel (vanilla), netctl, KDE Plasma (not minimal), gdm, grub2 and no additional software.

![anarchy](https://user-images.githubusercontent.com/5448916/34651730-6c298de8-f399-11e7-81ef-be36837b21e1.png)

Here's the log;

![anarchy2](https://user-images.githubusercontent.com/5448916/34651737-7d9bdce8-f399-11e7-96d3-e6eabffbc2db.png)

**Comment by condor2** [comment]
https://github.com/deadhead420/anarchy-linux/commit/fd17ebba7db6df5402f04d71c48a9123a7cbeaca

**Comment by BooBerry** [comment]
Will rebuild and test ASAP, thanks!

**Comment by condor2** [comment]
Just update script before run.

**Comment by BooBerry** [comment]
Yep, working now. Thanks.

**Comment by RichardPIS** [comment]
Problem still exists, I have changed the keyserver.
How update the script before installation?

**Comment by cyberstruggle** [comment]
same here

**Comment by tmsbrdrs** [comment]
I'm currently having the same issue. Is there a workaround?

**Comment by don-smith** [comment]
I'm also getting this error with the latest ISO. I suspect "root" is referring to the partition and I've tried a number of different ways to create it (auto and manual) and nothing seems to work. Guidance would be very much appreciated.

**Comment by erazemkokot** [comment]
@don-smith Thanks for submitting the report, but the original issue is very old, so can you please submit a new one with your log. Although the error message is still the same (it just means that an error occured), the underlying issue is probably different.
