### ISSUE TITLE
Error updating arch-anyhere

### ISSUE THREAD

**Issue by nt-jjrubio** [deadhead420/anarchy-linux#599]
error: no se pudo obtener el archivo «arch-anywhere.db» desde arch-anywhere.org: Could not resolve host: arch-anywhere.org

**Comment by FredBezies** [comment]
How to fix this.

1) sudo nano /etc/pacman.conf
2) go to the bottom of the file
3) Replace server line in [arch-anywhere] section by this:
Server = https://anarchy-linux.org/repo/$arch

Bug will be dead.
