### ISSUE TITLE
Whatever happened to the website?

### ISSUE THREAD

**Issue by notorand-it** [deadhead420/anarchy-linux#600]
I cannot reach arch-anywhere.org any more!

**Comment by BooBerry** [comment]
URL changed.

https://anarchy-linux.org/

**Comment by notorand-it** [comment]
I'd suggest for a redirect. Even Google is pointing to the old website

**Comment by notorand-it** [comment]
And i suggest also to add some more news in the home page.
The latest version is said to be 2.2.9 but when I go to the download page I read 1.0.0.
It's clear why are at a transition point. But some more details would help the newcomers.

**Comment by nastybuttler322** [comment]
If someone kind of gives the site a shout out on twitter, the google crawlers will pick it up faster.
