### ISSUE TITLE
Wrong Kernel version in install image

### ISSUE THREAD

**Issue by mkzero** [deadhead420/anarchy-linux#601]
Just tried to install on a UEFI PC but the installer aborts because it can't load vfat. The problem is that the running kernel of the installer is older than the installed kernel modules in /lib/modules.

This problem seems to exist on the GUI ISO only, the CLI ISO worked flawlessly and had the correct kernel modules on disk.

**Comment by deadhead420** [comment]
Thanks for the report. I just tested in vbox set to UEFI mode and the kernel seems to match the modules (both version 4.14.11-1). I'm also able to run mkfs.vfat -F32 without any issues.

**Comment by deadhead420** [comment]
Will test on real hardware

**Comment by mkzero** [comment]
Just recently used the installer again, seems like this is fixed.
