### ISSUE TITLE
Add "bépo" layout Keyboard

### ISSUE THREAD

**Issue by bepolymathe** [deadhead420/anarchy-linux#602]
Dear anarchists,

I did an installation of anarchy 1.0.0 yesterday and I missed something: the possibility of installing my favorite keyboard layout "bepo" during the installation. 
https://en.wikipedia.org/wiki/Keyboard_layout#B%C3%89PO
Of course, I was able to do it afterwards via the keyboard configuration but it would be great to be able to do it right from the installation. 
Thank you in advance.

**Comment by deadhead420** [comment]
As far as I can tell its in the list of keymaps as "fr-bepo" or "fr-bepo-latin9". You have to select from the list of keymaps under "other". However searching for it in the list made me realize the list is out of order. Fixed it by adding sort.
