### ISSUE TITLE
Running `pacman -Syu` can't find arch-anywhere.db

### ISSUE THREAD

**Issue by Kishaihd** [deadhead420/anarchy-linux#603]
When I try to update my system using 
`pacman -Syu`
I get the following: 
```
:: Synchronizing package databases...
 core                                   126.8 KiB  2.06M/s 00:00 [####################################] 100%
 extra                                 1627.5 KiB   397K/s 00:04 [####################################] 100%
 community                                4.0 MiB   576K/s 00:07 [####################################] 100%
 multilib                               166.7 KiB   490K/s 00:00 [####################################] 100%
error: failed retrieving file 'arch-anywhere.db' from arch-anywhere.org : Could not resolve host: arch-anywhere.org
error: failed to update arch-anywhere (download library error)

```
I've been getting this message for several days.
All other repositories update just fine.

**Comment by nemanjan00** [comment]
Domain has changed.

**Comment by Kishaihd** [comment]
Do you know how to change the default server?

**Comment by condor2** [comment]
Don`t use old arch anywhere 2.2.9 iso. Use Anarchy 1.0 iso...

**Comment by Kishaihd** [comment]
It's not a fresh install, I've been using this for over a year. Yeah, I could do  a fresh install, but that's a pain I'd like to avoid if possible.

**Comment by nemanjan00** [comment]
Just change /etc/pacman.conf... 

Server = https://anarchy-linux.org/repo/$arch

**Comment by ChTBoner** [comment]
Same thing here. I changed the [arch-anywhere] entry in my /etc/pacman.conf, but I get a 404 on the URL above. I supposed the name of the db will be a problem too and won't be called "arch-anywhere.db".

**Comment by ChTBoner** [comment]
Fixed it like this in my pacman.conf
replace the [arch-anywhere] part with this:

```
[anarchy]
Server = https://anarchy-linux.org/repo/$arch
SigLevel = Never
```

**Comment by Kishaihd** [comment]
Thank you @nemanjan00 and @ChTBoner for being helpful. That fixed it for me as well!
