### ISSUE TITLE
Suggestion: Skip partitioning option

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#606]
I would code this myself, and see if you would want it added. But my school semester just started, and it would take me a while to figure out how to do this.

I think a skip partitioning option would be a good feature to add, in case the drive was already partition from an install that only failed due to a package not being available.

**Comment by nastybuttler322** [comment]
and a back option, incase a wrong option was selected due to pushing ok out of habit after a while.

**Comment by deadhead420** [comment]
You can do this just by using manual partitioning. Regardless the partitions you want to use for the install must be selected. However if using manual partitioning the drive doesn't have to be re-partitioned but you still have to select a partition to use as root (or boot, etc...). I understand what you're saying by having an option to just skip everything all together but this wouldn't really work as the installer has no way of automatically knowing what partition you want as root (or boot, etc...). If the install fails it is possible to restart and use manual partitioning and mount everything manually.

**Comment by nastybuttler322** [comment]
Oh cool. Dude I just kept wiping my drive lol.
