### ISSUE TITLE
No Xintrc file created

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#607]
Pushing cancel on adding a display manager appears to skip creating the Xintrc file. It MIGHT create it, but I wasn't presented with the prompt to let me know that it was, so I just restarted the install process.

**Comment by deadhead420** [comment]
It will always add the xinitrc no matter what (with or without a DM). I updated the script so it will now show the startx message when you select cancel from display manager menu. Thanks for reporting.

**Comment by nastybuttler322** [comment]
Ah cool. I was hoping that's all it was.
