### ISSUE TITLE
Tag versioning inconsistency

### ISSUE THREAD

**Issue by JoshuaRLi** [deadhead420/anarchy-linux#613]
Hi @deadhead420, thanks for anarchy-linux.

Currently, 1.0.0 is available for [download](https://anarchy-linux.org/download), but there is no tagged commit in the repository that reflects that version change. I'd appreciate it if you could tag a 1.0.0 release.

**Comment by deadhead420** [comment]
Thanks for the reminder! I'll be sure to keep up with it.
