### ISSUE TITLE
Archlinux cleanup : removing nvidia304xx from installer.

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#616]
Nvidia 304xx driver are now dropped. See these mails in arch-commits mailing list: 

https://lists.archlinux.org/pipermail/arch-commits/2018-January/446508.html
https://lists.archlinux.org/pipermail/arch-commits/2018-January/446509.html
https://lists.archlinux.org/pipermail/arch-commits/2018-January/446510.html
https://lists.archlinux.org/pipermail/arch-commits/2018-January/446511.html

**Comment by deadhead420** [comment]
Removed 304xx

**Comment by FredBezies** [comment]
As this is removed, let's close this bug.
