### ISSUE TITLE
Suggest: Wallpaper folder location

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#621]
In the live gui iso, if the user right clicks on the desktop for Monitor 0, and selects 'Desktop Settings,' then the use is presented with the customized Anarchy backgrounds.

But if the user does the same for Monitor 1, the user is presented with the default XFCE wallpapers.

If the wallpapers are moved into the XFCE folder, and the anarchy wallpaper folder removed, then the user will be presented with all of the wallpapers regardless of which monitor the user is changing it for.

**Comment by condor2** [comment]
So you want all walppapers in `usr/share/baackgrounds/xfce` ?

**Comment by nastybuttler322** [comment]
Or the pictures folder, so they're real easy to find.

**Comment by condor2** [comment]
Wallpapers was moved in xfce folder.
