### ISSUE TITLE
pacman.conf

### ISSUE THREAD

**Issue by mobi2201** [deadhead420/anarchy-linux#622]
What to replace now the lines 
[arch-anywhere]
Server = http://arch-anywhere.org/repo/$arch 
in /etc/pacman.conf

**Comment by condor2** [comment]
`[anarchy]
Server = https://anarchy-linux.org/repo/$arch
SigLevel = Never`

**Comment by mobi2201** [comment]
Is everything so simple ?! :) I and expected, but the beginner in Linux, was afraid to break system. Thank you very much and sorry for my english ...
