### ISSUE TITLE
Suggestion: wifi fix for GUI installer

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#623]
A few ideas that may help as a solution to the wifi problem with the GUI installer.

I think I can do this myself, but I'm not sure. I've never done any of this. I'm also working on my capstone.

Idea #1)
Add a line to .xinitrc file to execute the installer application, right after the desktop environment executes. Unless doing so would cause it to not open in a window that is accessible for the end user. Pretty much, just launch a window of the installer application, right after the desktop environment starts. So the user's attention is drawn towards it right away.

The installer itself should be edited, so that it prompts the user by asking him or her, if he or she would like to set up a wifi connection, right at the start of the process. If 'Yes' is selected, then the wifi-menu program could be executed within the installer window. Once connected, the installer can continue without having to stop by telling the user there is no network connection. I recommend this, because if the user currently sets a wifi connection up through the Network Manager applet on the desktop's task bar, the installer will not use the connection.

If this causes conflict with the internet connection for the desktop, due to it relying on network manager, then that's why I have idea number 2.

Idea #2)
Switch over to netctl applications instead of Network manager, for the Desktop. If a taskbar front end would be made for wif-menu netctl application, if one does not yet already exist, then this could share the wireless profile with the installer application. If these two can not share profiles, then a zsh script needs to be made. That's why I added a third idea.

Idea #3)
The shell script, probably zsh script, needs to execute at the point once the wireless connection is established within the installer application window, and the the wifi-menu application ends. It needs to execute right BEFORE the regular installer application executes within the same window. So, this script should be executed in between the ending of the wifi-menu exiting with an established connection, and before the start of the installation procedure.

The script needs to copy the wireless profile FROM the netctl or systemd folder, (I can't remember where it's locacted), of the user that the installer exists under, TO the user that the Desktop environment is running under. (The capitalization is meant for clarity.)

This shell script should erase the user id after the ":" symbol, up to the newline character. It should over write it with the ID of the user that this new file now resides under. Before it does this, it should make the appropriate directory, or directories, if they do not yet exist.

**Comment by nastybuttler322** [comment]
I had a request for info on how to make this an iso, then I read a file that obviously is responsible for doing that job.

**Comment by JustMeErazem** [comment]
@nastybuttler322 The GUI version is [no longer supported](https://github.com/deadhead420/anarchy-linux/issues/766#issuecomment-451733688), so please close the issue.
