### ISSUE TITLE
Wrong file extension for background wallpaper - Anarchy-Carbon_Mesh

### ISSUE THREAD

**Issue by honze-net** [deadhead420/anarchy-linux#625]
While comparing Anarchy Linux with Arch Linux I found out, that you copy wallpaper to `/usr/share/backgrounds/anarchy/`. I looked at them, but `Anarchy-Carbon_Mesh.jpeg` was not rendering correctly in my file browser.
```
$ file /usr/share/backgrounds/anarchy/Anarchy-Carbon_Mesh.jpeg 
/usr/share/backgrounds/anarchy/Anarchy-Carbon_Mesh.jpeg: PNG image data, 3840 x 2160, 8-bit/color RGBA, non-interlaced
```
Please rename `Anarchy-Carbon_Mesh.jpeg` to `Anarchy-Carbon_Mesh.png`.
You also might want to review #526 and #527.

**Comment by condor2** [comment]
You men not show as thumbnail?

**Comment by honze-net** [comment]
Yes.
