### ISSUE TITLE
wifi is harder to set up than for Arch

### ISSUE THREAD

**Issue by nastybuttler322** [deadhead420/anarchy-linux#626]
English:

I went ahead and did a regular archbuild for the first time, so that I understood everything better with the system, and so that I knew how to do more customizations.

The wifi in the build that I did works fine.

I installed Anarchy two different times on a separate drive, at first just to do some partition edits on the f2fs partitions that the installer iso, and my knoppix iso, prevented me from doing, even with f2fs-tools installed on knoppix.

-The first install, after I chose netctl, and not networkmanager, I selected 'yes' to the wifi software prompt. Then, once installed, I executed wifi-menu. It detected the networks that were available, and I selected one, as well as entered the password. The virtual terminal output a message for me to update the profile, or make a profile, I think after I tried to ping google.com. It notified me to check the profile for systemctl.

I did all of this with the Anarchy build that I was using, before I decided to actually see what it took to do an Arch build. So, I do know about the profiles. It took me a long time to figure out how to set all of that up though. 

The Arch build that I assembled, did not require me to do all of that with the profiles. 

At this point, I figured that maybe the wifi software that I selected 'yes' to, during installation, may have been intended for people running networkmanager with a desktop.

-The second install, after I chose netctl, I selected 'no' to the wifi software. Then, once I booted into this install, I attempted to execute wifi-menu. I was notified that I needed wpa_supplicant, which I had to install as well in the Arch build on my other drive.

This time, wifi-menu will not detect any networks. 

I know HOW to set up wifi the way that I installed Anarchy the first time that I described here. But this process with Anarchy is actually more complicated than it is to set it up for a standard Arch build. It's probably the only thing that's more complicated. It took me a long time to figure out where those profiles were, and I'm pretty sure that I had to copy one to a particular directory for each wifi connection that I wanted to use, as well as renaming the profiles, and editing their contents.

It's not a bad thing to learn all of that stuff, but it's not convenient for people that don't want a desktop environment. I am guessing that the second install needs me to enable my wifi device. 

I wish I could pinpoint the cause of this to actually help, but I'm clueless.

Română:

Am mers mai departe şi a făcut o archbuild regulate pentru prima dată, astfel încât am înţeles totul mai bine cu sistemul, şi astfel încât am ştiut să facă mai multe particularizări.

WiFi în construi că am făcut works fin.

Am instalat anarhie două ori diferite pe o unitate separată, la început doar pentru a face unele editări partiţie pe partiţiile f2fs că ISO de instalare, şi meu Knoppix ISO, ma împiedicat de a face, chiar şi cu f2fs-Tools instalat pe Knoppix.

-prima instalare, după ce am ales netctl, şi nu NetworkManager, am selectat "Da" la internet Wi-fi prompt. Apoi, odată instalat, am executat WiFi-meniu. Acesta a detectat reţelele care au fost disponibile, şi am selectat unul, precum şi a intrat parola. Virtual Terminal de ieşire un mesaj pentru mine pentru a actualiza profilul, sau de a face un profil, cred că după ce am încercat să ping Google.com. M-a anunţat să verific profilul pentru systemtl.

Am făcut toate astea cu anarhie construi pe care am fost folosind, înainte de am decis să văd de fapt, ceea ce a luat pentru a face un arc construi. Deci, eu ştiu despre profiluri. Mi-a luat mult timp să dau seama să setaţi toate că până totuşi.

Arcul construi pe care am asamblat, nu au nevoie de mine pentru a face toate că, cu profiluri.

În acest moment, m-am gândit că poate software-ul WiFi pe care am selectat "Da", în timpul instalării, poate au fost destinate pentru persoanele care rulează NetworkManager cu un desktop.

-a doua instalare, după ce am ales netctl, am selectat "nu" la software-ul WiFi. Apoi, odată ce am pornit în această instalare, am încercat să execute WiFi-meniu. Am fost notificat că am nevoie de wpa_supplicant, pe care am avut de a instala, precum şi în arcul de a construi pe cealaltă unitate mea.

De data aceasta, WiFi-meniu nu va detecta orice reţele.

Ştiu să înfiinţeze WiFi modul în care am instalat anarhie prima dată când am descris aici. Dar acest proces cu anarhie este de fapt mai complicat decât este să-l înfiinţeze pentru un arc standard de construcţie. Probabil e singurul lucru mai complicat. Mi-a luat mult timp să dau seama în cazul în care aceste profiluri au fost, şi eu sunt destul de sigur că am avut de a copia unul la un anumit director pentru fiecare conexiune WiFi pe care am vrut să o utilizaţi, precum şi redenumirea profiluri, şi editarea conţinutului lor.

Nu este un lucru rău pentru a afla toate aceste lucruri, dar nu este convenabil pentru persoanele care nu doresc un mediu desktop. Sunt ghicitul că a doua instalare are nevoie de mine pentru a permite dispozitivul meu WiFi.

Aş vrea să pot localiza cauza de a ajuta de fapt, dar eu sunt clueless.

**Comment by condor2** [comment]
What wifi module you have?

**Comment by nastybuttler322** [comment]
Network controller: Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter (rev 01)
	Subsystem: Hewlett-Packard Company RTL8188EE Wireless Network Adapter
	Kernel driver in use: rtl8188ee
	Kernel modules: rtl8188ee

**Comment by nastybuttler322** [comment]
Do you think Anarchy installs something that conflicts with another module for Udev?

**Comment by nastybuttler322** [comment]
I saved the install log, if that would help. I wasn't thinking when I overwrote the previous install log with this new one.

**Comment by condor2** [comment]
So after install networkmanager not show wifi networks?

**Comment by nastybuttler322** [comment]
I didn't install network manager. I noticed that's what was used in the desktop GUI iso, and I think the installer mentioned (or I read it somewhere) that it's mainly for a desktop environment. I'm not running a desktop environment, so I use netctl.

**Comment by nastybuttler322** [comment]
After I installed wpa_supplicant, no wifi networks appeared. I rebooted into my standard arch build, and all the networks are up, and my device works fine. 

I BELIEVE, that this means that I need to use systemctl to enable the wireless device profile. But I did not have to do that for the non-Anarchy build.

**Comment by condor2** [comment]
Ah....you mean using arch linux iso? and not anarchy-iso?

**Comment by nastybuttler322** [comment]
No no, I mean Anarchy. I had no issues with the regular Arch linux. This is only an issue I ran into with Anarchy.

**Comment by nastybuttler322** [comment]
I just set up Arch regular yesterday. I did not have to configure a systemctl profile, I didn't have to enable the wireless interface. I just had to install wfi-menu, and wpa_supplicant.

**Comment by nastybuttler322** [comment]
There may have been a little more to what I did to set up wifi on my regular Arch install, but I know that I did not have to do near as much as I do in order to set it up with Anarchy without using a desktop environment.

**Comment by nastybuttler322** [comment]
@condor2 Am actualizat totul cu o traducere din cauza bariera de limbă

**Comment by condor2** [comment]
Just write in English. Google translate is not so good.

**Comment by JustMeErazem** [comment]
@nastybuttler322 Do you still have this problem using the 1.0.4 release?

**Comment by JustMeErazem** [comment]
Closing since the issue refers to an older version and there was no reply from the issuer. @nastybutler322 reopen if needed.
