### ISSUE TITLE
No mdadm support in live ISO

### ISSUE THREAD

**Issue by s7relok** [deadhead420/anarchy-linux#630]
Hello,

I wanted to do an install using mdadm raid. Unfortunately it seems buggy in the live ISO

What's happened : Wanted to do an install with Intel Rapid Storage (fake raid), activated and configured in the BIOS. On Linux, it's managed with mdadm.

When I boot the live ISO, there's no automounting of already configured (in the bios) raid, because the module mdadm is not loaded. We can't load it manually too. For comparison, arch official ISO mounts the thing, and we can do the install transparently (pacstrap in the /dev/md(something).

What you did : Booted the live ISO, trying to find /dev/md(something). Did a lsmod to see if the module is loaded, it's not. Tried to load it with 'modprobe mdadm' with root.

Solution : activate mdadm on boot, or giving the possibility to load modules in live mode

![screenshot_20180120_184858](https://user-images.githubusercontent.com/30574235/35186399-d51a6dca-fe13-11e7-9f41-0c976788ca5d.png)

**Comment by andrew-grechkin** [comment]
Are you sure it should be `modprobe mdadm` not `modprobe md_mod`?

**Comment by s7relok** [comment]
Maybe, I will test.

But the thing that the module for raid is not launched at start is still a problem. That's not a huge ram eater and can be loaded at start for more convenience

**Comment by notorand-it** [comment]
I don't think this is going to work.
Whatever you configure in the BIOS will let the OS to see a single device, like /dev/sda.
In this case mdadm won't show anything usefule as the OS is seeing just a single device.
mdadm works on simple devices, not on "hardware" RAID devices!
On the other side, if you disable BIOS RAID, you'll be able to setup yours with mdadm.

I think this bug can be closed.

**Comment by paulie-g** [comment]
@notorand-it That's incorrect. A number of fakeraid "devices" are managed with dm/md.

**Comment by JustMeErazem** [comment]
@s7relok Hi, are you still interested in this?

**Comment by JustMeErazem** [comment]
Closing the issue since there doesn't seem to be any interest in fixing it. If you want this resolved, reopen the issue.
