### ISSUE TITLE
Missing image on readme

### ISSUE THREAD

**Issue by Angristan** [deadhead420/anarchy-linux#631]
Hey,

Just wanted to let you know that one of the images is missing : 

https://github.com/deadhead420/anarchy-linux/blame/master/README.md#L18

https://anarchy-linux.org/images/anarchy-splash.png

It was this one (from archive.org):
![](https://web.archive.org/web/20171226121748if_/https://camo.githubusercontent.com/d8ce17f9057d56257ecff736a98b33ab15f746f1/687474703a2f2f617263682d616e7977686572652e6f72672f696d616765732f616e61726368792d73706c6173682e706e67)

**Comment by rbatllet** [comment]
Yes, the left image is broken:

![screen shot 2018-01-23 at 12 22 49](https://user-images.githubusercontent.com/3993987/35273246-382cc90a-0038-11e8-92d8-607c5b93feb4.png)
