### ISSUE TITLE
Blank blue screen, right after I start the installation script?

### ISSUE THREAD

**Issue by n17h31sm** [deadhead420/anarchy-linux#640]
Hello there, I have been using archanywhere/anarchy for some time and I never had a problem, however I got a new laptop ASUS ROG with nvidia gtx 950m and the thing is as follows: I disabled secure boot and restarted, then I get on the anarchy screen, and I fetchmirrors, then update it, and after that I run the script with the 'anarchy' command then the screen changes to blue with no text just the text underscore marker blinking and it hangs there and nothing happends. What might be the cause?

**Comment by privatefound** [comment]
rog's is fu**** bad... i have it too still have problem with linux.... 2000$ pc for nothing

**Comment by JustMeErazem** [comment]
I'm closing this since there is not enough info to fix the problem, it's almost certainly an issue with the hardware. Try a different distro and report back if you're interested in a fix. Reopen the issue if so.

**Comment by cyb3rturtle** [comment]
@n17h31sm hi! have you resolved the issue or just changed a distro?
