### ISSUE TITLE
anarchy-local.db URL not working

### ISSUE THREAD

**Issue by dsvoid** [deadhead420/anarchy-linux#642]
I've heard I should use https://anarchy-linux.org/repo/$arch as the Server field for anarchy-local in pacman.conf. but that just gets me a 404. Any hints? Thanks for your time.

**Comment by condor2** [comment]
[anarchy]
Server = http://anarchy-linux.org/repo/$arch
SigLevel = Never

**Comment by FredBezies** [comment]
Should be closed, now?
