### ISSUE TITLE
KDE cannot be installed: kdenetwork-kopete not found?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#644]
See this forum thread:

https://anarchy-linux.org/forums/viewtopic.php?id=290

**Comment by condor2** [comment]
There is no kdenetwork-kopete in the script. I think is a KDE bug, but I will test.

**Comment by FredBezies** [comment]
Indeed. Tested myself too today. Full kde install in anarchy. Then I installed kde-applications in running kde. No error. Closing this bug.
