### ISSUE TITLE
Menu Probleme

### ISSUE THREAD

**Issue by Thava-P** [deadhead420/anarchy-linux#647]
During the installation I did not notice the presence of the option anarchy-advanced is a little hidden. I knew it because of a youtuber. Pls made the option visible.

**Comment by FredBezies** [comment]
You should change bug title to: make anarchy-advanced option easier to find.

**Comment by FredBezies** [comment]
Looks better now. Fix is coming.

![virtualbox_anarchy - test_21_09_2018_08_32_23](https://user-images.githubusercontent.com/8571419/45864066-0ce7a400-bd79-11e8-9df8-1dd2cde4bf76.png)

**Comment by FredBezies** [comment]
This bug can now be closed.
