### ISSUE TITLE
archlinux 32 anarchy

### ISSUE THREAD

**Issue by masrourmouad** [deadhead420/anarchy-linux#648]
hi, i own an 2009 PC that did no support 64bit, can anarchy Linux build or create a way to build anarchy Linux 32 ?
thanks.

**Comment by ljoli** [comment]
@masrourmouad : in fact, it's possible to create an iso for 32bits ( i686) 

$./anarchy-creator.sh 
Usage options for: anarchy-creator
	-a|--all)	create cli and gui iso
	-c|--cli)	create anarchy cli iso
	-g|--gui)	create anarchy gui iso
  --i686)		create i686 iso
  --x86_64)	create x86_64 iso (default)

**Comment by masrourmouad** [comment]
thanks
