### ISSUE TITLE
Adding inxi to software list makes installation fail

### ISSUE THREAD

**Issue by izzy** [deadhead420/anarchy-linux#654]
Adding inxi will end the installation, the log reporting that inxi could not be found.

**Comment by FredBezies** [comment]
Inxi moved to AUR: https://aur.archlinux.org/packages/inxi/

Either it needs to be added to anarchy repository or it needs to be remove from installation script.

**Comment by FredBezies** [comment]
You can close this bug as inxi is available on anarchy repository now.
