### ISSUE TITLE
Installation failed with live usb iso

### ISSUE THREAD

**Issue by ghost** [deadhead420/anarchy-linux#657]
When I tried to install anarchy linux (in uefi) from the live usb version, installing the programs at root failed...

I tried several times and it never worked.

While booting from the minimal installer (non-live), it worked the first time.

**Comment by miguelcaravantes** [comment]
Same error en cli versión, the detail of error is "key "CEB167EFB5722BD6" could not be looked up remotely"

**Comment by SirPacker** [comment]
I managed to fix this by doing "gpg --receive-keys CEB167EFB5722BD6". Despite the error, it is a valid key
