### ISSUE TITLE
Network manager applet not showing pop up for asking password

### ISSUE THREAD

**Issue by LoveChocoCat** [deadhead420/anarchy-linux#658]
When i want to connect on wifi with the applet there is something missing that is the pop up dialog for the password so when i connect to my ssid in the first time the notification show you're not connected to the ssid and i realize where is the pop up. Yeah, i can live with setting up the ssid config first then connect but it'll be more convenient to just have pop up dialog. So i hope in later development please fix this bug or whatever broken thing this is. Thanks for listening

**Comment by condor2** [comment]
You can install gnome-keyring for wifi popup password.

**Comment by LoveChocoCat** [comment]
thanks for the help
