### ISSUE TITLE
It seems fbterm can show Chinese word with out xorg

### ISSUE THREAD

**Issue by spphinslove** [deadhead420/anarchy-linux#660]
https://wiki.archlinux.org/index.php/Fbterm

**Comment by condor2** [comment]
Chinese will work only for GUI mode, but chinese language wasn`t updated.

For CLI is hard to work with fbterm
https://github.com/deadhead420/anarchy-linux/issues/45

**Comment by JustMeErazem** [comment]
Closing since it won't be fixed.
