### ISSUE TITLE
xfce desktop is unresponsive on keyboard and mouce input HP Z820

### ISSUE THREAD

**Issue by romanstingler** [deadhead420/anarchy-linux#666]
on the hp z820 workstation the xfce desktop opens normally but then I can just watch the minutes on the clock change but no input from mouse or keyboard is recognized.

the CLI installer is fine and afterwards the installation is fine either.

Furthermore, the live version is not diplayed correctly on displayport 4K with a RX 560.

**Comment by scjeti** [comment]
This is the same issue as issue #574, #576, and likely several other similar ones, which still haven't been FIXED. ?
https://github.com/deadhead420/anarchy-linux/issues/574

**Comment by JustMeErazem** [comment]
Since it's an upstream issue and GUI isn't currently available I'm closing it.
