### ISSUE TITLE
Plan for new release soon ?

### ISSUE THREAD

**Issue by 3kynox** [deadhead420/anarchy-linux#667]
Hey!

I see interesting things on the commits, any ETA ?

It could be great to give a small tutorial on how to build by ourselves.

Thanks anyway :)

Keep up the good work!

**Comment by condor2** [comment]
Download, cd in folder then run `./anarchy-creator.sh` from Terminal

**Comment by deadhead420** [comment]
Working on it. My apologies have been busy doing other things. I'll try to have an update ASAP

**Comment by 3kynox** [comment]
Thanks @condor2 @deadhead420 !
Awaiting the update, cheers :)

**Comment by FredBezies** [comment]
@cyberstruggle looks like this bug appears right after arch-install-scripts v18 were released.

https://www.archlinux.org/packages/extra/any/arch-install-scripts/

**Comment by FredBezies** [comment]
As bug #637 is now closed, a new set of ISO could be produced.

**Comment by 3kynox** [comment]
w00t!
