### ISSUE TITLE
The French keyboard layout isn't set after the installation

### ISSUE THREAD

**Issue by Lokidari** [deadhead420/anarchy-linux#669]
I installed the Anarchy Linux with Budgie Desktop.
On the installation, I set : 
French language with fr_FR keyboard layout. 

After the installation I boot and the keyboard was set to the English keyboard. That's same for the OpenBox Desktop.
NB : I don't have this issue when I choose the XFCE Desktop.

**Comment by FredBezies** [comment]
Duplicate of bug #532

**Comment by alexisju** [comment]
`sudo localectl set-x11-keymap fr`

**Comment by condor2** [comment]
Should work...because is already that command in script....

`arch-chroot` "$ARCH" localectl set-x11-keymap $keyboard &>/dev/null`

**Comment by alexisju** [comment]
Maybe the locale id is not correct.. 

I have the same issue with belgian settings during the installation.

I always need to do a `sudo localectl set-x11-keymap be` after install (even just to login lightdm or ssdm).

**Comment by felsokning** [comment]
FWIW, I've run into the same problem with the Swedish (sv) keyboard mapping[s]. 

Putting my workaround here, for anyone else that runs into the same problem[s]: 

I've found that, after the install, if I change the VC Keymap to se-latin1, the X11 Layout changes (pc105, I think it is) and my keys (e.g.: ö,ä,å, etc.) work after a reboot from that point forward. 

I can't seem to find se-latin1 as an option during install, however, so you should approach this problem with the expectation that _the key mappings will fall-back to the US keyboard lay-out until a suitable Swedish keyboard mapping is applied_. (It's especially important to keep this in mind when configuring passwords.)

**Comment by JustMeErazem** [comment]
Closing since it's a duplicate of #638, track the progress there.
