### ISSUE TITLE
Can't boot into minimal cli

### ISSUE THREAD

**Issue by Moquo** [deadhead420/anarchy-linux#675]
Hello,
today I wanted to install Anarchy. But there's a problem: It says that it can't find `/dev/disk/by-label/ANARCHYV100`. In `/dev/disk/` there's no `by-label` directory. I also tried flashing it on my usb with different programs on linux (dd) and windows (etcher, win32diskimager, rufus). Im booting this stick over UEFI. I tried booting the official Arch Linux ISO from https://www.archlinux.org also, and the same error occured but with the following path: `/dev/disk/by-label/ARCH_201806`. I also tried booting it over another USB port. Everytime i get into an interactive shell. Does anybody know a fix or this a bug? I would appreciate it if anybody could help me with this problem :)

**Comment by condor2** [comment]
No details...

- notebook or desktop...
- not flash drive model...

**Comment by Moquo** [comment]
I have a Acer Spin SP513-52N and I'm using a Sandisk Ultra USB 3.0 flash usb stick.

**Comment by FredBezies** [comment]
Did you try with another USB stick?

**Comment by Moquo** [comment]
Yes, I already tried another usb stick.

**Comment by toudli** [comment]
Hi, did you try to rename the name of the USBkey volume to ANARCHYV100? it worked for me.
