### ISSUE TITLE
Repo db returns 404? 

### ISSUE THREAD

**Issue by nemanjan00** [deadhead420/anarchy-linux#684]
Did you guys change something? 

```
error: failed retrieving file 'anarchy.db' from anarchy-linux.org : The requested URL returned error: 404
error: failed to update anarchy (unexpected error)
```

**Comment by condor2** [comment]
We generate repo packages on server using a script and has some bugs. I will try to fix repo

**Comment by gugatxr** [comment]
Now is working. =D

**Comment by niklasnolte** [comment]
```
error: failed retrieving file 'anarchy.db' from anarchy-linux.org : Failed to connect to anarchy-linux.org port 443: Connection refused
error: failed to update anarchy (download library error)
error: failed to synchronize all databases
```
this is my error now :upside_down_face:

**Comment by condor2** [comment]
Now possible Dylan forgot to pay domain :rofl:

**Comment by niklasnolte** [comment]
working well again for me, thanks!

**Comment by vitorveiga** [comment]
Not working for me too. Same as @niklasnolte .

**Comment by niklasnolte** [comment]
some unstable servers there? :joy:

**Comment by Jazz-Man** [comment]
Not working for me:
```
error: failed retrieving file 'anarchy.db' from anarchy-linux.org : Failed to connect to anarchy-linux.org port 443: Connection refused
error: failed to update anarchy (download library error)
error: failed to synchronize all databases

```

**Comment by Mjolinir** [comment]
anarchy-linux.org appears to be down

**Comment by jwilson64** [comment]
Any word on why this is still down?

**Comment by condor2** [comment]
We need (to buy) a server....

**Comment by jwilson64** [comment]
I wish I were in a position to donate to the cause. While we can point to the Arch repos I don't think that resolves the real issue because this affects everything involved here. Has there been anything asking for donations put out there? I feel like this distro is a pretty good help with those of us wanting to use arch but not wanting to go through the install process.

**Comment by FredBezies** [comment]
Still broken for me... Ouch!

**Comment by bramkok** [comment]
The website and repository are online again.
