### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by elikoga** [deadhead420/anarchy-linux#685]
Websites "anarchy-linux.org" and "arch-anywhere.org" are both down.
Flagged in the whois entry

**Comment by linusheinz** [comment]
Torrent would be really nice

**Comment by KobaltMR** [comment]
[Try it](https://www.facebook.com/groups/archanywhere/permalink/2054693078192194/)

**Comment by LandKingdom** [comment]
Nice. That post was edited just 19 hours ago. This issue can be closed now. If, for any reason, the post is deleted or not accessible, you can still access the google drive folder [here](https://drive.google.com/drive/folders/11pfA_AzbyNazOLw1Z8vf9dzLvMZs8mo6).

**Comment by hhain** [comment]
Website still down, updates from anarchy-db repository not possible? Is some one going to fix this issue, or is anarchy linux dead?

**Comment by pbck** [comment]
Guys, do you need a set of free VMs in US and EU?
If you provide the requirements, I would gladly supply them. 
Let me know.

**Comment by FredBezies** [comment]
Site is back! Yes :)
