### ISSUE TITLE
Replacing fetchmirrors by reflector ?

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#690]
Eschwartz filled a deletion request on AUR requests mailing list to delete fetchmirrors.

https://lists.archlinux.org/pipermail/aur-requests/2018-July/025625.html

> [...]In general I don't see any reason for this to exist, especially as
[community]/reflector exists.

So what about replacing code and using reflector instead of fetchmirrors?

**Comment by Seeder101** [comment]
Yes. fetchmirrors is outdated reflector is the new thing
I highly suggest to replace fetchmirrors with reflector

Thank you

**Comment by FredBezies** [comment]
Fetchmirrors is removed.

https://lists.archlinux.org/pipermail/aur-requests/2018-August/025962.html

What about a fix now? :D

**Comment by FredBezies** [comment]
I only need to fix key 6 in .zshrc to get everything working :)

**Comment by FredBezies** [comment]
Kinda dirty, but it works.

**Comment by FredBezies** [comment]
Fetchmirrors is back. This bug is fixed. Closing this issue.
