### ISSUE TITLE
[Anarchy Xfce] Pantheon music link is not working

### ISSUE THREAD

**Issue by FredBezies** [deadhead420/anarchy-linux#694]
I installed an Anarchy Xfce desktop with last anarchy installer. When I tried to launch Pantheon Music, I noticed link was incorrect.

New pantheon-music executable is: /usr/bin/io.elementary.music

See: https://www.archlinux.org/packages/community/x86_64/pantheon-music/

**Comment by condor2** [comment]
Fixed.

**Comment by FredBezies** [comment]
So closing it :)
