### ISSUE TITLE
No torrent at website

### ISSUE THREAD

**Issue by andersfylling** [deadhead420/anarchy-linux#701]
over at your website there is no torrent, even though theres a link.

https://anarchy-linux.org/download

**Comment by condor2** [comment]
I know

**Comment by whoamin** [comment]
any comments?

**Comment by condor2** [comment]
1. I have only 2GB space for all anarchy files on my server.

**Comment by andersfylling** [comment]
So you only have 2GB space on your server for anarchy files, but does seeding require extra space?

Are you limited by upload bandwidth?

**Comment by who-am-1** [comment]
You can publish magnet only, and seeding from home internet. That's enough, I guess

**Comment by who-am-1** [comment]
army of seeders will help you. I can seeding with 100mbit 24/7 absolutely easy

**Comment by psrcek** [comment]
I'll join the seeders with 100 Mb/s :P 24/7 unlimited.

**Comment by andersfylling** [comment]
So was this fixed? There were comments but those got deleted for some reason.

Since it's arch, quite a few prefer a distributed copy as that feels safer. And potentially provides faster download speeds.

I don't understand understand why this was closed?

**Comment by condor2** [comment]
Happy now?

https://anarchy-linux.org/iso/anarchy-cli-1.0.1-x86_64.iso.torrent

**Comment by andersfylling** [comment]
It returns a http code of 404

**Comment by unixfox** [comment]
@condor2 do you have the file of the .torrent for the iso of anarchy because the website is down?
