### ISSUE TITLE
Did the installation stop?

### ISSUE THREAD

**Issue by andersfylling** [deadhead420/anarchy-linux#702]
Version: 1.0.0

"Failed retrieving file 'yaourt-1.9-1-any.pkg.tar.xz' from anarchy-linux.org : The requested url returned error: 404"

But when i check the log file "/tmp/anarchy.log", the previous entry was just downloading software i selected during the anarchy installation. So I have to ask if it just cancelled the entire instalation because it couldnt download one optional software?

Edit: it does cancel the installation and you have to do everything again.

**Comment by andersfylling** [comment]
Tried again now. Got a new error. When it asks which i3 package (gaps, blocks, wm, etc.) It inputs "xfe", a file manager which i selected during the instal process.

**Comment by andersfylling** [comment]
Tried again. Skipped adding additional software. Still got cancelled during install. 

When installing i3blocks, the signature is unknown and therefore causes an error.

**Comment by andersfylling** [comment]
Try #4: skipped both additional software and desktop/wm managers. It installed successfully.

**Comment by andersfylling** [comment]
Doing additional software after installation does not yield an error. However none of the targets selected (arch-wiki-cli, yaourt, fetchpkg, fetchmirrors) were found (as stated in log).

**Comment by andersfylling** [comment]
The last install gave me a system where its unable to mount the encrypted device. Im left with "waiting 10 seconds for /dev/lvm/lvroot"..."can't access tty"

**Comment by condor2** [comment]
Update script before run installer.

Yaourt is dead

**Comment by andersfylling** [comment]
How?

**Comment by condor2** [comment]
Use CLI iso and press 2.

**Comment by andersfylling** [comment]
Downloaded the latest cli iso. Hit update before install. Install still cancels out due to i3blocks being corrupted.

**Comment by andersfylling** [comment]
Tried again. With the same process as the comment above. Except i dropped i3.

Got a new error. Its unable to install linux base devel.

**Comment by JustMeErazem** [comment]
@andersfylling Some packages were dropped in 1.0.4 and yaourt was replaced with yay, so this problem likely isn't occuring anymore. I'm gonna close this issue, but if you try the installation again and the problem arises again, please reopen the issue.
