### ISSUE TITLE
lxqt pgp keys

### ISSUE THREAD

**Issue by noraj** [deadhead420/anarchy-linux#709]
1) Some gpg keys are missing or outdated, so LXQT is making the whole install to fail.
2) In case of something prompting user interaction during `pacman -S` why not prompt the user instead of making the whole install fails ? Because restarting the whole process from the beginning take some time.

**Comment by JustMeErazem** [comment]
Seems to work fine in 1.0.4 (the keyring was most likely updated in the later Arch image).

**Comment by noraj** [comment]
the keyring may be updated, but in case of a fails of any software it will still make the whole install fails.

**Comment by JustMeErazem** [comment]
True, I'll make a separate issue for that. Something like "Don't stop installation if package download fails".

But this could mean that you still end up with a broken install though.

**Comment by noraj** [comment]
Yeah it will up to the user to decided, if its a critical core package it will end in a trashed system but if just a minor optional utility it would avoid a total reinstall just for it.

**Comment by JustMeErazem** [comment]
I guess we could implement that, yeah.

Could you create the issue please.
