### ISSUE TITLE
Parabola GNU/Linux and/or Linux Libre Kernel support?

### ISSUE THREAD

**Issue by GeitHub** [deadhead420/anarchy-linux#71]
First of all, big thanks for this essential tool. You've made Arch accessible to even a total novice like myself.

I imagine you're putting more focus on bugfixes/translation/ARM support, but if you find the time I'd appreciate the option to install Parabola. I've tried migrating using the steps provided on their wiki here https://wiki.parabola.nu/Migration_from_the_GNU/Linux_distribution_of_Arch#Complete_migration but I haven't been able to make it work as of yet. 

The result that I'm looking for is an easy setup Parabola with the minimal KDE DE, the latter was easy to install after following the steps in this post on your forum here https://arch-anywhere.org/forums/viewtopic.php?id=53 and if I do manage to figure out how to switch I'll be sure to add a thread over there with the steps.

Thanks again

**Comment by JustMeErazem** [comment]
@condor2 This issue could probably also be closed since it would require a separate project to make it possible or it would increase the complexity a lot.
