### ISSUE TITLE
the anarchy repo is entirely unsigned

### ISSUE THREAD

**Issue by Kommynct** [deadhead420/anarchy-linux#711]
This is an insanely bad security issue, I don't know where to properly post this, but, this needs fixed.

**Comment by cjmccormick** [comment]
Yeah, one of the reasons why I just installed vanilla arch. looks like anarchy is dead pretty much :/ Miss the old installer. Would be nice to see it come back under the name of Anarchy Linux or something or a different name. Love the CLI gui installer.

**Comment by Kommynct** [comment]
the cli installer is still available, and I always use it.

I dunno man, I might just switch to void whenever I can.

**Comment by FredBezies** [comment]
Looks like anarchy repository is working again. Closing this bug?

**Comment by condor2** [comment]
We think to remove entire aar repo.
