### ISSUE TITLE
User not known to the underlying authentication module

### ISSUE THREAD

**Issue by demlak** [deadhead420/anarchy-linux#713]
I just tried to generate an anarchy iso via latest master.zip `anarchy-creator.sh -a`
Got same Problem like this: https://github.com/deadhead420/anarchy-linux/issues/712

I was able to boot the final iso after editing startcommand in bootloader to find the correct disk by label.

But booting gui iso gets into a loop when automatic login should start, with following error:
`User not known to the underlying authentication module`

booting the cli-iso works (after fixing startcommand in bootloader), without this loop and/or error message.

btw. 
filesize of `anarchy-1.0.1-x86_64.iso` is just 569MB
filesize of `anarchy-cli-1.0.1-x86_64.iso` is 556MB

**Comment by FredBezies** [comment]
About iso size: you won't get a full GUI iso until bug #637 is fixed.

**Comment by lecterx** [comment]
demlak,please, what commands you used for booting to cli installer, how I fix it to boot ?

**Comment by demlak** [comment]
boot as normal.. wait for the "waiting 30 seconds for device..." fails.
then, there is a prompt where you can check the name of the DVD/USB/CD_ROM/Whatever by this command:
`ls -dev/disk/by-label/`
actualy this results in `ANARCHYV101`

then reboot. 
at bootloader use key "tab"
edit the archisolabel "ARCH_201809" (or any other laber) to ANARCHYV101 and press enter

**Comment by FredBezies** [comment]
@demlak thanks! You gave me infos needed to fix boot issue!

**Comment by demlak** [comment]
Your welcome =) I'm suprised. I thought you already knew where the problem was =) 
I tested your fix and can confirm, that it works.

now, we should go back to topic =)

**Comment by cjmccormick** [comment]
You are on a roll  FredBezies! Kudos to you my friend.

**Comment by FredBezies** [comment]
Well, kinda... I'm disappointed to see this project going the way of the dodo :(

**Comment by FredBezies** [comment]
A little work in progress... Just look at kernel version and date :)

![virtualbox_test_14_09_2018_11_38_44](https://user-images.githubusercontent.com/8571419/45542643-c80cbc00-b812-11e8-9f86-992839d47bd5.png)

**Comment by FredBezies** [comment]
My fix for bug #637 is now added. You just need to build a new ISO to use GUI installer.

Closing this bug, so?
