### ISSUE TITLE
Default .bashrc has a broken alias for du

### ISSUE THREAD

**Issue by tgharib** [deadhead420/anarchy-linux#745]
Here is what happens when you try to use `du`:

    [owner]: ~>$ du -sh .nv/
    sort: read failed: .nv/: Is a directory
    [owner]: ~>$ sudo !!
    sudo du -sh .nv/
    [sudo] password for owner: 
    9.1M	.nv/

It only works when ran as root. [This comment](https://www.reddit.com/r/archlinux/comments/9ks64k/du_only_works_when_ran_as_root/e71e9bm/) describes the problem and has a fix.

**Comment by JustMeErazem** [comment]
@tgharib I've tried using the fix locally by adding `du() { du -ach "$@" | sort -h; }` to my bashrc, but it always seem to not work and for some reason use a lot of cpu, which forces me to reboot.

Try if this fix works locally for you, otherwise it would be best to just remove the `du` alias.

**Comment by JustMeErazem** [comment]
@condor2 The pull request was merged so this issue can be closed.
