### ISSUE TITLE
Wifi internet connection problem when installing Anarchy

### ISSUE THREAD

**Issue by WhiteLord** [deadhead420/anarchy-linux#752]
The installation process was conducted on a HP Zbook 15.
The wireless adapter is Intel Corporation Wireless 7260.
I am able to run any distributions of Linux with gui and connect to wireless networks thus conducting an installation process.

After chosing a network, the user never gets prompted for a password entry. In my case, I "tricked" the gui by editing the wifi settings and entering the WPA2 passphrase.
This, however is not enough for the installation to take place. After the user clicks on the "install" icon, one is prompted with the message that one cannot begin installation because of lacking network connectivity (despite being connected by the gui).
The installer quits.

To avoid this and continue the installation process, the user should execute the following commands with **root** access:
- Execute `ifconfig` in order to define a network interface that will be used. From now on, we will refer to the wireless interface the user has chosen as **<network_interface_name>**
- Execute `wifi-menu -o` - in order to generate a profile located at **/etc/netctl/**. In this step, it is important to state that a user should not input a profile name, containing special characters and/or dashes, quotes, etc. Plain text and numbers only.
- Execute `vim /etc/anarchy.conf` or chose another text editing software in order to delete the ` | grep wpa` string on line 480 in the abovementioned file
- Execute `ip link set <network_interface_name> down` - shut down the network interface
- Execute `netctl start <network_interface_name>` - There you can have 2 results. Either the user gets no errors and continues with installation or has to execute `killall wpa_supplicant`, then `ip link set <network_interface_name> down`, followed by `netctl start <network_interface_name>`

This will let the user continue with the installation process.
The use of the specified wifi interface will require nothing more - the user is able to connect to other networks.

**Comment by JustMeErazem** [comment]
@WhiteLord I'm guessing you're refering to the GUI installation of Anarchy. It isn't currently supported, so please try the installation on the latest 1.0.4 CLI release. You should be able to connect to WiFi easily.

**Comment by JustMeErazem** [comment]
Closed because of inactivity
