### ISSUE TITLE
xorriso not found

### ISSUE THREAD

**Issue by pholat** [deadhead420/anarchy-linux#760]
xorriso is being used but not checked for existence, would be nice to inform user at the beginning of iso-creator script to install.

**Comment by FredBezies** [comment]
It is a depend of archiso... And part of libisoburn.

```
pacman -Qi archiso
Name            : archiso
Version         : 39-1
Description     : Tools for creating Arch Linux live and install iso images
Architecture    : any
URL             : https://projects.archlinux.org/archiso.git/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : make  arch-install-scripts  squashfs-tools  libisoburn
                  dosfstools  lynx
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 244.00 KiB
Packager        : Gerardo Exequiel Pozzi <djgera@archlinux.org>
Build Date      : Sun Aug 26 23:08:01 2018
Install Date    : Mon Aug 27 08:59:23 2018
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
And libisoburn:

```
pacman -Qi libisoburn
Name            : libisoburn
Version         : 1.5.0-1
Description     : frontend for libraries libburn and libisofs
Architecture    : x86_64
URL             : https://dev.lovelyhq.com/libburnia
Licenses        : GPL2
Groups          : None
Provides        : xorriso  xorriso-tcltk
Depends On      : libburn  libisofs  readline
Optional Deps   : tk: for xorriso-tcltk frontend [installed]
Required By     : archiso
Optional For    : grub
Conflicts With  : None
Replaces        : None
Installed Size  : 1695.00 KiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Sat Oct 6 10:13:41 2018
Install Date    : Sat Oct 6 10:32:37 2018
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

This bug can be closed as invalid, I think. @condor2 ?

**Comment by pholat** [comment]
Hi, I'm creating the iso on ubuntu so there might be different dependencies. Can it be that other things won't work as well if I use "bad distro" to do so? :)

**Comment by FredBezies** [comment]
It won't work. Archlinux and Ubuntu are not based on same binary packages.

**Comment by pholat** [comment]
@FredBezies I thought that if it's a bash script using Linux tools distro doesn't really matter. And it looked like it to me - as it run without failure after getting `archiso` on my ubuntu. 

I believe there is nothing about distro to use to run the script in README.md. Adding that to docs might be valuable then.

**Comment by deadhead420** [comment]
Hey guys. Sorry for the inactivity. Hoping to do an update sometime this week as long as I have the time

**Comment by bless-9** [comment]
This is good news glad your back please update thanks!!!

**Comment by condor2** [comment]
@pholat It really matter.

Not all distro has the same packages name, or commands, or repo URL etc...
