### ISSUE TITLE
pacstrap failure on '-f' switch

### ISSUE THREAD

**Issue by pholat** [deadhead420/anarchy-linux#761]
When installing through cli installation fails on pacstrap (in install_base.sh)
There is '-firmware' in base_install variable which is being read as '-f' switch which is why it's failing.

As a quick and dirty solution removing '-firmware' with sed worked ok, but it doesn't feel right.

**Comment by FredBezies** [comment]
Looks like you did not update installer.

See this fix added back on November 5th, 2018: https://github.com/deadhead420/anarchy-linux/commit/923a4d9717f6ac08507e51479523aa841b960e31

So this bug can be easily closed.

**Comment by pholat** [comment]
@FredBezies I  was quite sure it was the master version from the day it was posted, so if the fix came in 5th November I should be using that. It would be kind of you if you let me to verify it by friday/saturday when I'll have a bit of time to do so.

**Comment by Mayurifag** [comment]
@FredBezies I had the same issue when I tried to install Zen kernel via Anarchy on Virtualbox. Everything is okay if I try to install regular kernel, which I don't want to have.

So you say we have to update the installer. Where can we read about how to do that? Do we have to do this manually? Is there an automatical way? I guess the installer has to self-update from master branch before doing anything..

**Comment by Mayurifag** [comment]
@FredBezies thanks! That helped. Now I have #753 error. Probably thats okay to add the «Workarounds» section at readme and the progressbar for updates in anarchy also.

**Comment by xNNism** [comment]
Hmm I got `anarchy error: invalid option '-f' ==> ERROR: Failed to install packages to new root`
 after updating it turned to  `... invalid option --overwrite ...`

(Deleting --overwrite at line 49 in `/usr/lib/anarchy/install_base.sh` quick 'n dirty fixed it )
