### ISSUE TITLE
deepin and kernel LTS incompatibility

### ISSUE THREAD

**Issue by noraj** [deadhead420/anarchy-linux#763]
deepin dependencies requires kernel >= 4.20 
example https://www.archlinux.org/packages/community/x86_64/deepin-anything/
so selecting deepin with older kernel like LTS (4.19) will fail.

**Comment by FredBezies** [comment]
Just open a bug report on archlinux bugtracker, not here.

**Comment by FredBezies** [comment]
Oops! I was wrong. Sorry.

**Comment by condor2** [comment]
Seem that issue was fixed.
