### ISSUE TITLE
Install frozen at grub config

### ISSUE THREAD

**Issue by noraj** [deadhead420/anarchy-linux#764]
Anarchy installer is blocked at this (grub config making) for more than 30min.

![image](https://user-images.githubusercontent.com/16578570/50567162-f8388600-0d41-11e9-8168-538ccb66f2c9.png)

Is the install totally crashed but not error is displaying ? Is the installation continuing but the display step is frozen to grub install ? Rebooting I won't have logs anymore, so I can't tell you more.

**Comment by pnedkov** [comment]
Do you install on a LVM?
BTW, you can switch to another terminal to collect logs.

**Comment by noraj** [comment]
I should have checked that when this happened. But instead I quit and began a True ArchLinux install. I will never be able to give more info.
