### ISSUE TITLE
Live-GUI url 404

### ISSUE THREAD

**Issue by lalovzg** [deadhead420/anarchy-linux#766]
[This url](https://anarchy-linux.org/iso/anarchy-1.0.0-x86_64.iso) goes to a 404
What is the link to the GUI version?

**Comment by condor2** [comment]
Use CLI.

**Comment by JustMeErazem** [comment]
Hi, does it make sense to even support the GUI version in future releases, since this is just an installer and the CLI version is smaller and very simple to use?

**Comment by JustMeErazem** [comment]
@condor2 This issue can easily be closed, as it is resolved.
