### ISSUE TITLE
Failed retrieving "anarchy-local.db" from disk on Anarchy cli 1.0.3

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#772]
After compiling Anarchy 1.0.3 CLI and trying it out in a Virtual Machine I get this error (summarized, because I can't copy the text):

```
...
failed retrieving file "anarchy-local.db" from disk: Couldn't open file /usr/share/anarchy/pkg/anarchy-local.db

error: failed to update anarchy-local (download library error)
...
```

`/etc/pacman.conf` also includes this text:

```
[anarchy-local]
Server = file:///usr/share/anarchy/pkg
SigLevel = never
```

The mentioned *pkg* directory is empty.

**Comment by condor2** [comment]
you have AUR enabled on you pc?

**Comment by JustMeErazem** [comment]
The PC I compiled it on?

Yes (It's a Virtual Machine with Antergos and has AUR support + yay installed if that helps).

**Comment by condor2** [comment]
Virtualbox?

Try to recreate the ISO and see if you ave errors when is made.
I don't have this issue.

**Comment by JustMeErazem** [comment]
I didn't get this error once I recompiled the ISO, but now I get the error `error: failed to update core/extra/community (no servers configured for repository)`

**Comment by condor2** [comment]
I made 1.0.2, you can test
https://www.anarchylinux.org/download/

**Comment by JustMeErazem** [comment]
It works in 1.0.2, thank you :)
