### ISSUE TITLE
Install hangs on grub-mkconfig -o /boot/grub/grub.cfg

### ISSUE THREAD

**Issue by blackham** [deadhead420/anarchy-linux#773]
Creating a LVM + LUKS disk and it hangs during the install at: grub-mkconfig -o /boot/grub/grub.cfg
Bug is documented [here](https://bbs.archlinux.org/viewtopic.php?id=242594)

I hacked around it by running from a different terminal. But it would be nice if the install would just work. (also if the installer would do "pacman -Sy archlinux-keyring" so I didn't have to). 

```
mkdir /mnt/hostlvm
mount --bind /run/lvm /mnt/hostlvm
chroot /mnt /bin/bash
ln -s /hostlvm /run/lvm
```

**Comment by blackham** [comment]
NOTE: after running grub-mkconfig manually, I can kick the installer into continuing by running /usr/lib/anarchy/configure_boot.sh

**Comment by pnedkov** [comment]
Could you please test this #774

**Comment by demyxco** [comment]
@blackham I tried your steps but didn't work. It would say "/bin/bash not found." Trying to do this on the live USB.

**Comment by blackham** [comment]
@demyxco  "/bin/bash not found."  -> It might work if you do /bin/zsh  (I'm not a fan of how zsh clobbers my command when I tab complete) But I'd suggest using a different distro like Antergos or find an OLD .iso of anarchy (arch-anywhere) before the bug was introduced. 

The bug is with LVM + LUKS. LUKS by itself installs without issue. 
The Antergos installer lets you use LUKS without LVM.

* Antergos has the same issue as arch-anywhere (sorry, anarchy) when trying to use both LVM and LUKS. The only advantage Antegos has is the installer lets you select/unselect LVM and LUKS (encryption) independently. So you can choose to skip LVM and keep encryption. 

** This bug shows itself on my Dell laptop (both legacy and UEFI) and an ESXi VMware install attempt.

**Comment by demyxco** [comment]
@blackham yeah I went with Antergos, closest thing to a vanilla arch install.

**Comment by fwanky** [comment]
Having the same issue, what'd you mean by opening another terminal? Is there some gui installer/

**Comment by fwanky** [comment]
Any eta on a fix for this?:/

**Comment by MorosithIi** [comment]
I met with similar situation during installation of Gentoo through livecd. 
The following steps helps me out of the situation:
First mount your rootfs. I mount it to /mnt/gentoo. 

Step two:
```mkdir mnt/gentoo/run/udev
```
Step three 
```
mount - - rblind/run/udev /mnt/gentoo/run/udev
mount - - make-rslave /mnt/gentoo/udev
```
Then you can chroot into your rootfs and run grub-mkconfig.
Hope this could help.

**Comment by JustMeErazem** [comment]
@blackham the 'archlinux-keyring' part should probably work now, test and report back. But regarding the 'grub-mkconfig' hanging, that is an Arch issue, not an Anarchy one. So unless they fix it, it won't be fixed here. I'm closing the issue for now, reopen it if needed.
