### ISSUE TITLE
Install fails: "Cannot connect to anarchy-linux.org on port 443"

### ISSUE THREAD

**Issue by bundito** [deadhead420/anarchy-linux#775]
I go through the installer, making all my sensible and normal choices, only to have it bomb at the final step. 
```
Error: failed retrieving file anarchy.db from from anarchy-linux.org port 443
Error: failed to update anarchy (download library error)
Error: failed to synchronize all databases
ERROR: failed to install packages to new root
```
I tried `https://anarchy-linux.org:443` by hand, and indeed, it fails.

I'm using the ISO that I found on GitHub - v1.0.1 from Sept 2018. Is there a newer ISO somewhere? Something else I can try?

**Comment by Arax20** [comment]
Maybe the website isn't fully set up yet

**Comment by condor2** [comment]
Update script before install. Anarchy  repo was removed and that domain lost.

**Comment by TheNekromate** [comment]
I had a similar issue with the updated version except for the anarchy.db part.Also it said that i(the script should use  --overwrite instead of --force.

**Comment by trwnh** [comment]
New domain is anarchylinux.org, and Anarchy repos were removed per recent commits.

**Comment by JustMeErazem** [comment]
@bundito Try the [newest 1.0.2 iso](https://www.anarchylinux.org/download/) and see if it works there (the repo was successfully removed).
