### ISSUE TITLE
Anarchy CLI 1.0.2 failed to commit transaction 

### ISSUE THREAD

**Issue by Dellums** [deadhead420/anarchy-linux#777]
I have tried a wide variation of settings and no matter what I get the same error: 

> downloading yay-9.1.0-1-x86_64.pkg.tar.xz...
error: failed to commit transaction (unexpected error)
Errors occurred.  no packages were upgraded.
==> ERROR: Failed to install packages to new root
2019-03-01 22:40 : Install failed: please report to developer

I have tried running 
`anarchy -u `
`pacman -Sy archlinux-keyring`
before starting the installer as well

**Comment by condor2** [comment]
I don't have this issue when I run anarchy -u or pressing 2 (anarchy -u )

**Comment by Dellums** [comment]
Sorry, I didn’t have any issues running anarchy -u either I was just informing you I tried that step.  However, removing yay from line 184 solved my problem.  I was able to install anarchy on the first try.  Thanks :)
