### ISSUE TITLE
KDE version

### ISSUE THREAD

**Issue by dandydon414** [deadhead420/anarchy-linux#778]
any chance to offer KDE desktop rather than having to install it after the fact? thanks

**Comment by condor2** [comment]
You mean to be a customized Anarchy KDE, like Anarchy XFCE...etc?

**Comment by dandydon414** [comment]
Yes, where KDE is offered during installation

**Comment by condor2** [comment]
You can install for now only Minimal KDE Plasma and Full KDE Plasma.

**Comment by dandydon414** [comment]
do you mean install KDE after a normal installation with another desktop?  If that's what you mean, I actually ran  sudo pacman  -S plasma and installed KDE after I installed Anarchy with the cinnamon desktop. For the most part it worked but IMO it was a little messy having 2 DEs. The experience was not as smooth as a KDE from scratch distro.

**Comment by condor2** [comment]
You can install only KDE when use Anarchy...

**Comment by dandydon414** [comment]
I didn't see that as an option.. If I recall I saw only Gnome, XFCE, Cinnamon, Budgie and something else. I didn't see KDE.....I do an install again to verify

**Comment by condor2** [comment]
Anarchy Advanced-->Next...Clean Desktop....
![screenshot_2019-03-05_00-41-33](https://user-images.githubusercontent.com/14251939/53767769-74d11780-3edf-11e9-8300-ac5153b150f4.png)

**Comment by dandydon414** [comment]
okay ....found the KDE option but after all was said and done, didn't start up in virtualbox....gonna try a regular install on a spare ssd.  thanks alot for all you help....you da man!

**Comment by dandydon414** [comment]
took a bit of tinkering but finally got it up and running
![image](https://user-images.githubusercontent.com/48139014/53779998-66c7ca80-3ed0-11e9-9cc1-ae6908c83898.png)

A million thanks pal.
