### ISSUE TITLE
Install is successful, but no option to boot into Anarchy

### ISSUE THREAD

**Issue by gluntn** [deadhead420/anarchy-linux#779]
OS: Windows 10 Home
PC: Lenovo Yoga 720 (i5-7200 / Intel HD 620)
HDD: Samsung NVMe (MZVLW256HEHP-000L2)

First things first: I wrote the Anarchy Linux ISO to a USB drive using Rufus. I tried installing, but the installer didn't find my harddrive the first time around. I switched from RAID to ACHI in the BIOS. I should also note that I have, in preparation for Linux, shrunk my main C: partition so that Linux could have free reign over a partition.

Now Anarchy found my NVMe disk, and I chose all the desired settings, chose the newly created partition to install Anarchy to and all seemed well. I then go through the installation process with no hick-ups, until I get to the screen telling me that the installation was successful, and I chose to restart.

Here's where the problem starts: there's simply no option for me to choose a bootloader for Anarchy. I get back into Windows, and under the partition manager I still find the partition I had prepared for Linux, but it's completely empty and of type RAW, for some reason.

Trying to restart the computer and mashing F10/F12 to get into the boot loader shows only the Windows bootloader. Is there something I maybe forgot to do?

**Comment by PandaFoss** [comment]
How did you perform the disk partitioning?

**Comment by JustMeErazem** [comment]
@gluntn Do you still have this problem?

**Comment by JustMeErazem** [comment]
Closed as it referenced an old version and there was no reply from the issuer.
