### ISSUE TITLE
Download link on site still includes wpa_actiond

### ISSUE THREAD

**Issue by TheAnarchoX** [deadhead420/anarchy-linux#784]
Hi, im migrating from windows to arch and wanted to use Anarchy as my guide along the way, so i downloaded the iso and made a bootable usb, now the problem is it keeps getting stuck on de pacman install because it can't find wpa_actiond, due to my current 'disability' of having a windows machine i cant recreate the iso mysql, any thoughts?The filename of the iso is "anarchy-cli-1.0.2-x86_64.iso"

**Comment by mmwwaaaa** [comment]
You should update build before you perform installation:
a. boot *.iso
b. press 2 to update
c. $PROFIT

**Comment by meyer1994** [comment]
@mmwwaaaa It solved for me.
