### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by dandydon414** [deadhead420/anarchy-linux#787]
getting this error during installation.  even when adding another user aside from root
![WhatsApp Image 2019-04-25 at 11 46 04 PM](https://user-images.githubusercontent.com/48139014/56784115-a619e580-67b4-11e9-9eb0-6020becf174b.jpeg)

**Comment by mmwwaaaa** [comment]
Hi
Please post output of said log.
Thanks

**Comment by dandydon414** [comment]
![WhatsApp Image 2019-04-26 at 3 18 36 PM](https://user-images.githubusercontent.com/48139014/56834298-a4910180-6836-11e9-84c2-975699ddd107.jpeg)

**Comment by tony-ze-yi** [comment]
When you boot anarchy, enter 2 into terminal immediately; that will update the installer script

**Comment by dandydon414** [comment]
thanks.that worked

**Comment by tony-ze-yi** [comment]
welcome

**Comment by JustMeErazem** [comment]
@dandydon414 Since it worked, will you close the issue?

**Comment by dandydon414** [comment]
my bad.  I'll remember for the next time
