### ISSUE TITLE
Missing package "wpa_supplicant" in live-usb, so that wifi-menu does not work

### ISSUE THREAD

**Issue by vinzochek** [deadhead420/anarchy-linux#788]
I only have a wireless connection, which is why I can not install Anarchy Linux.

**Comment by condor2** [comment]
You have tried using wifi-menu command?

**Comment by vinzochek** [comment]
wifi menu does not start, asks to install wpa_supplicant.  I installed wpa-supplicant locally via pacman -U, and it all worked.

**Comment by vikmary** [comment]
I found the same problem while trying to install Anarchy Linux with WPA network: no wpa_supplicant package.

It is a known issue of 2019-05-01 arch release.
Fix https://bugs.archlinux.org/task/62516
Discussion https://amp.reddit.com/r/archlinux/comments/bjeunv/arch_iso_20190501_does_not_have_wpa_supplicant/

Please update arch version to 20190502
