### ISSUE TITLE
Boot menu hangs with Logitech unified receiver

### ISSUE THREAD

**Issue by sudoquai** [deadhead420/anarchy-linux#791]
I've tried to install anarchy linux on an old system with a logitech unified receiver connected.

Unfortunately the boot menu doesn't recognize keyboard and mouse so there is no chance to continue with the installation.

I've found out that mouse + keyboard works with bios and tried another similar distro which has a timeout included at the boot menu (boot menu does not work with mouse and keyboard, too).

After the boot menu passed mouse and keyboard works as usual so it seems there is a bug in the boot menu itself.

I would suggest to include a timeout in the boot menu, so it simply continues when there is no keyboard select - this would solve the issue.

**Comment by PandaFoss** [comment]
I just made a Pull Request (#792). I hope it solves the problem.

**Comment by sudoquai** [comment]
Thank you very much - very helpful.

**Comment by PandaFoss** [comment]
The problem has been apparently solved: #792 
However, the new ISO image has not yet been published. You can wait for the new version to be published on the [official website](https://www.anarchylinux.org/download/), download the code and compile it yourself or I can compile it and upload it to Google Drive if you need it soon.

**Comment by sudoquai** [comment]
Thank you very much ! :)

Am Sa., 8. Juni 2019 um 09:03 Uhr schrieb condor2 <notifications@github.com
