### ISSUE TITLE
Installation Hanging

### ISSUE THREAD

**Issue by dandydon414** [deadhead420/anarchy-linux#793]
I've been trying to install and lately it just stops while downloading files.  Internet is working fine.  Starts downloading then after awhile it just hangs.  Yesterday even option 2 "update the script", hung as well. It's like it's not connecting to wherever it downloads the files from.

**Comment by PandaFoss** [comment]
Inside the installer, try the `iptest` command. When executing it, it will display three options. If it's a laptop, enter `3` to connect to a Wi-Fi network. In any case, after making sure you are connected to the internet, you can enter `iptest` with the options `1` and `2` to check that you are really connected and control the connection speed. You can post the result here.

**Comment by dandydon414** [comment]
thanks for the quick reply.  I have to assume that my internet connection (hard wired) is okay since, shortly thereafter I installed Arch then ArcolinuxD with no connection issues and both installed fine.  But I will make another attempt with Anarchy and post results.

**Comment by dandydon414** [comment]
tried again and although it was very slow, it finally installed. maybe it had something to do with the deepin files.  One thing I did notice was that after installation and booting into the deepin de, installs of apps in the terminal were crawling.  I selected the default mirrors during the initial install and noticed 2 servers.  I had a mirrorlist that I generated from the Arch wiki and it had many more servers.  I copied that file into the mirrorlist and then everything downloaded much much faster.  In the end all is well.  Anarchy is hands down is the best minimal installer for Arch Linux.

**Comment by PandaFoss** [comment]
It is true what you say. Although the original problem was solved, I'm going to investigate what the problem is by which it only uses two servers.
Thank you!

**Comment by dandydon414** [comment]
FYI
# Server list generated by rankmirrors on 2019-05-29
Server = http://mirrors.evowise.com/archlinux/$repo/os/$arch
Server = http://mirror.rackspace.com/archlinux/$repo/os/$arch
These are the servers when selecting default during install

**Comment by PandaFoss** [comment]
Yesterday I did the test in a virtual machine and the same thing happened to me. Apparently it is solved executing fetchmirrors before beginning the installation. However, i will continue to investigate the root of the problem.
