### ISSUE TITLE
/mnt/usr/share/pixmaps/archlinux.png error exist agian in 2019.06.01

### ISSUE THREAD

**Issue by ifa26416** [deadhead420/anarchy-linux#796]
after the 2019.06.02 update, the error with file /mnt/usr/share/pixmaps/archlinux.png exist agian. I tried to remove the package arch-wiki-cli but nothing happen, the error is still there.
![IMG_20190604_080030](https://user-images.githubusercontent.com/51348132/58844514-b66d8c00-86a1-11e9-9374-9a8815e37432.jpg)
i skipped the desktop setting and the problem were fixed. i found the pkg file of arch-wiki-cli in /usr/share/anarchy/pkg. is it the start point of the problem ?

**Comment by PandaFoss** [comment]
Try what I show in [this](https://github.com/deadhead420/anarchy-linux/issues/795#issuecomment-497974613) comment.

**Comment by ifa26416** [comment]
yeah, i tried it but the error still happen
i forgot that the problem happen when i try to install the openbox version of anarchy :)

**Comment by PandaFoss** [comment]
Have you tried deleting the package with pacman?
There is some step that you are doing wrong because if you delete `arch-wiki-cli` the conflict should disappear.

**Comment by ifa26416** [comment]
i tried it, but the error still happen, i also tried the anarchy anvanced option, but no anything fixed the error

**Comment by ifa26416** [comment]
I think i should record a video about that crazy problem and hope it'll be helpful

**Comment by condor2** [comment]
arch-wiki-cli was removed until @deadhead420 will update PKGBUILD.
