### ISSUE TITLE
st is an AUR package, so therefore choosing it fails and errors.

### ISSUE THREAD

**Issue by MatthewCroughan** [deadhead420/anarchy-linux#798]
Apologies for the crude photo, I'm in a rush, hence why I'm using your lovely installer. I checked on my system, and `st` is not included anywhere but the AUR, and your scripts install this with `pacman`. So of course, pacman cannot find it, and suitably fails. This means you have to do the entire installer menu again. Thanks for your work!

![image](https://user-images.githubusercontent.com/26458780/59734917-40ddf000-924b-11e9-8929-c93092e73fed.png)

**Comment by condor2** [comment]
st was removed

**Comment by MatthewCroughan** [comment]
@condor2 Is this issue worth closing?

**Comment by MatthewCroughan** [comment]
@condor2 But did you actually fix it? What commit?

**Comment by MatthewCroughan** [comment]
https://github.com/deadhead420/anarchy-linux/commit/3a433f68f539f3e7888098b74fe816b25b91738f

If you put the issue number inside your commit message, it would have shown here without you having to type a comment.
