### ISSUE TITLE
wifi-menu error

### ISSUE THREAD

**Issue by ueberchild** [deadhead420/anarchy-linux#801]
After Anarchy installation `sudo wifi-menu` has this output:
`nl80211: kernel reports: Attribute failed policy validation
Failed to create interface p2p-dev-wlp0s20f3: -22 (Invalid argument)
nl80211: Failed to create a P2P Device interface p2p-dev-wlp0s20f3`
But it disappears after `killall wpa_supplicant`
Next, when I try to choose my wi-fi in opened menu, it writes:
`CONNECTION FAILED`

`systemctl status "netctl@wlp0s20f3\\x2dDSL_2640NRU.service"` output:
`The interface of network profile 'wlp0s20f3-DSL_2640NRU' is already up
netctl@wlp0s20f3\x2dDSL_2640NRU.service: Main process exited, code=exited, status=1/FAILURE
netctl@wlp0s20f3\x2dDSL_2640NRU.service: Failed with result 'exit-code'.
Failed to start Networking for netctl profile wlp0ss20f3-DSL_2640NRU.
`
And `journalctl -xe` has almost the same, and also a line `Defined-By: systemd`

Disabling dhcpcd and removing netctl profiles with reboot doesn't help. Although, I have second laptop with Arch (another hostname), here I have no problems with Internet.

Tried installing Anarchy with both netctl and networkmanager, both have this problem.

Error is on a completely new HP Probook 450 G6, had no problems with wi-fi during Anarchy installation.
________
Although I had the same 2 error lines about p2p when installing Anarchy from iso. But all packages were installed successfully.
________
Ethernet works. Wi-fi not.

**Comment by ueberchild** [comment]
Although I had the same 2 error lines about p2p when installing Anarchy from iso. But all packages were installed successfully.

**Comment by ueberchild** [comment]
Ethernet works. Wi-fi not.

**Comment by ueberchild** [comment]
This enabled my wi-fi:
`ip link set wlp0s20f3 down`
`netctl start wlp0s20f3-DSL_2640NRU`

**Comment by ueberchild** [comment]
I noticed that once my Wi-Fi started without these two commands and even without `sudo wifi-menu`, and I did not enter them. But at the next startup after `sudo wifi-menu` I began to get this:
```
Scanning for networks... 
nl80211: kernel reports: Attribute failed policy validation
Failed to create interface p2p-dev-wlp0s20f3: -22 (Invalid argument)
nl80211: Failed to create a P2P Device interface p2p-dev-wlp0s20f3
failed
No networks found
```
I try to delete interface by 
`sudo ip link delete wlp0s20f3`
but I have
`RTNETLINK answers: Operation not supported`
and
```
systemctl status "netctl@wlp0s20f3\\x2dDSL_2640NRU.service"
```
has
```
Starting Networking for netctl profile wlp0s20f3-DSL_2640NRU...
Profile 'wlp0s20f3-DSL_2640NRU' does not exist or is not readable
netctl@wlp0s20f3\x2dDSL_2640NRU.service: Main process exited, code=exited, status=1/FAILURE
netctl@wlp0s20f3\x2dDSL_2640NRU.service: Failed with result 'exit-code'.
Failed to start Networking for netctl profile wlp0s20f3-DSL_2640NRU.
```
Again, only Ethernet works. Reinstall my OS?

**Comment by ueberchild** [comment]
Anarchy reinstalled, Wi-Fi password added, no results.

**Comment by JustMeErazem** [comment]
@ueberchild If your ethernet works, but your Wifi doesn't it's probably an issue with your wireless card driver. Try a different arch distro like [Manjaro](https://manjaro.org/) or [EndeavourOS](https://endeavouros.com/) and report back if wifi works there. If it does we need to find you a driver package for your card.
