### ISSUE TITLE
Key issues causing installation failure

### ISSUE THREAD

**Issue by basus** [deadhead420/anarchy-linux#802]
I have the installer repeatedly failing with key issues on various packages. I tried to run `anarchy -u` and `anarchy -k` and I get this error:
![image](https://user-images.githubusercontent.com/90872/59982633-7a17b680-95e3-11e9-83a3-e4ddcb35795c.png)

I have made sure that I don't have the `archi-wiki-cli` anywhere, as mentioned in other issues, but still get these errors.

**Comment by basus** [comment]
If I don't try to update anything and just run the installer, I get errors that look like this:
![image](https://user-images.githubusercontent.com/90872/59983136-e8f80e00-95e9-11e9-9555-87d51126a2e3.png)

**Comment by PandaFoss** [comment]
Before upgrading Anarchy, try this:
```
# pacman -Sy archlinux-keyring
# pacman-key --init && pacman-key --populate archlinux
# pacman-key --refresh-keys
```
Then update with `anarchy -u`.
If you don't execute `anarchy -k` doesn't install normally?

**Comment by basus** [comment]
I managed to get it to install somehow, with the minimal set of packages. I don't remember exactly how, but not running `anarchy -k` didn't work.
