### ISSUE TITLE
Steam won't launch 

### ISSUE THREAD

**Issue by TheAdventist** [deadhead420/anarchy-linux#807]
I decided to give Anarchy Linux a try (looking good and have very good experiences with Arch-based distros)

I tried several ways of installing/running Steam;
- Via the official Packages program, searched for steam and installed the official version (1.0.0.61-1), the same for the steam-native-runtime (same version number)
- Removed everything(including the /home/[user]/.steam and the /home/[user]/local/share/Steam):
   - Reinstalled it via Trizen (my cli choice, basically yay)
but both ways to no avail....

I suspect that something went wrong when installing the drivers for my GTX2060.
I believe it was the basic Mesa rendering engine (noveau) then I downloaded the official .run from the Nvidia site --> ./NVIDIA......run --no-x-check and afterwards it was upgraded to the official 390.xx branch (package manager), as seen as below:

An quick inxi -F shows this:
`System:
  Host: anarchy Kernel: 5.2.1-arch1-1-ARCH x86_64 bits: 64 
  Desktop: Xfce 4.13.5 Distro: Anarchy Linux 
Machine:
  Type: Desktop Mobo: ASRock model: AB350M Pro4 serial: <root required> 
  UEFI [Legacy]: American Megatrends v: P4.50 date: 01/08/2018 
CPU:
  Topology: Quad Core model: AMD Ryzen 3 1300X bits: 64 type: MCP 
  L2 cache: 2048 KiB 
  Speed: 2989 MHz min/max: 1550/3500 MHz Core speeds (MHz): 1: 2995 2: 1494 
  3: 1374 4: 1375 

Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 430.34 
  Display: x11 server: X.Org 1.20.5 **driver: nvidia** The driver is set to the official Nvidia driver
  unloaded: modesetting,nouveau resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 430.34 

Audio:
  Device-1: NVIDIA TU106 High Definition Audio driver: snd_hda_intel 
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.2.1-arch1-1-ARCH 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  driver: r8169 
  IF: enp31s0 state: up speed: 100 Mbps duplex: full mac: REDACTED
Drives:
  Local Storage: total: 1.82 TiB used: 47.70 GiB (2.6%) 
  ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB 
  ID-2: /dev/sdb vendor: Crucial model: CT1000MX500SSD1 size: 931.51 GiB 
  ID-3: /dev/sdc vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB 
Partition:
  ID-1: / size: 915.19 GiB used: 47.63 GiB (5.2%) fs: ext4 dev: 
  ID-2: /boot size: 201.3 MiB used: 70.0 MiB (34.8%) fs: ext4 dev:
  ID-3: swap-1 size: 512.0 MiB used: 0 KiB (0.0%) fs: swap dev: 
Sensors:
  System Temperatures: cpu: 29.9 C mobo: N/A gpu: nvidia temp: 45 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0% 
Info:
  Processes: 186 Uptime: 34m Memory: 15.66 GiB used: 1.01 GiB (6.4%) 
  Shell: zsh inxi: 3.0.34 
`

And launching Steam by command line shows this:
`Running Steam on anarchy rolling 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1563346602)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Installing breakpad exception handler for appid(steam)/version(1563346602)
Installing breakpad exception handler for appid(steam)/version(1563346602)

(steam:32388): Gtk-WARNING **: 18:34:06.799: Unable to locate theme engine in module_path: "adwaita",

(steam:32388): Gtk-WARNING **: 18:34:06.799: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Arc-Dark/gtk-2.0/main.rc:1090: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Arc-Dark/gtk-2.0/apps.rc:91: error: unexpected identifier 'direction', expected character '}'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  51
xerror_handler: X failed, continuing
**Steam: An X Error occurred**
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  50
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  52
xerror_handler: X failed, continuing
crash_20190718183405_1.dmp[32402]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190718183405_1.dmp
/home/REDACTED/.local/share/Steam/steam.sh: line 720: 32388 Segmentation fault      (core dumped) $STEAM_DEBUGGER "$STEAMROOT/$STEAMEXEPATH" "$@"
crash_20190718183405_1.dmp[32402]: Finished uploading minidump (out-of-process): success = yes
crash_20190718183405_1.dmp[32402]: response: CrashID=bp-9f71c2a5-98ff-401c-8bde-6087d2190718
crash_20190718183405_1.dmp[32402]: file ''/tmp/dumps/crash_20190718183405_1.dmp'', upload yes: ''CrashID=bp-9f71c2a5-98ff-401c-8bde-6087d2190718''
`

On other distro's (like MX Linux and Ubuntu 18.04.2) Steam works like an dream, so it cannot be an account/hardware issue. And with my ArchLabs linux (a while back) it also worked (although I'm not sure it was with my new Nvidia card)

Can somebody replicate it with an (new-ish) Nvidia card?

**Comment by JustMeErazem** [comment]
@TheAdventist Have you tried installing the `nvidia` package as described in the [NVIDIA article](https://wiki.archlinux.org/index.php/NVIDIA):

```
3. Install the appropriate driver for your card:

For GeForce 600-900 and Quadro/Tesla/Tegra K-series cards and newer [NVE0, NV110 and NV130 family cards from around 2010-2019], install the nvidia or nvidia-lts package.
If these packages do not work, nvidia-betaAUR may have a newer driver version that offers support.
There is also nvidia-llb-dkmsAUR, which is built from Nvidia's long lived branch.
For GeForce 400/500 series cards [NVCx and NVDx] from around 2010-2011, install the nvidia-390xx or nvidia-390xx-lts package.
For even older cards (released in 2010 or earlier), have a look at #Unsupported drivers.
```

**Comment by JustMeErazem** [comment]
@TheAdventist Check the solution described [here](https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update) and please report back.

The problem seems to be with the `swrast` driver, which is "the software renderer". Since I don't play Steam games I think you'll find more info on the askUbuntu website. Good luck.

**Comment by JustMeErazem** [comment]
Closing since there was no reply from the issuer. @TheAdventist reopen if needed.
