### ISSUE TITLE
SSL certificate issues

### ISSUE THREAD

**Issue by jesusrp98** [deadhead420/anarchy-linux#808]
I've installed Anarchy Linux in a couple machines recently, and both seems to have certificates problems. This hasn't happens to me never, even in older Anarchy installations.

This shows up when I run `pacman -Syu`:
```
error: failed retrieving file 'core.db' from osl.ugr.es : SSL certificate problem: unable to get local issuer certificate
```

**Comment by condor2** [comment]
Change that mirror.

**Comment by jesusrp98** [comment]
That solved my issue. Sorry I took a while to answer :)
Thanks!
