### ISSUE TITLE
[Request] Update website & forum

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#811]
The website and forum look very outdated and there haven't been any blog or forum posts in a long time.

This (possibly) leads to unnecessary hosting costs and it's harder for new users to find the needed info.

I propose a new static website be build, with a framework such as [Jekyll](https://jekyllrb.com/) or [Hugo](https://gohugo.io/), which would include a landing page with info and if needed a blog (posts for every new release would be nice).

By switching to this new static website and hosting it with github pages the cost for hosting would go down significantly as the only thing that would need to be paid for would be the domain name.

I have built some personal websites in hugo and would be willing to do all the work, like setting up the website and github pages, if you want it.

I really believe this would make the whole experience a lot better for new users as they wouldn't get overwhelmed with the old website and obsolete forum.

Edit: Also new version releases should be uploaded as github releases, so users don't have to check the website to see when a new version was released. The iso files can definitely be added to the releases along with a changelog, which further decreases the cost and bandwidth usage.

**Comment by condor2** [comment]
You can make if you want.

**Comment by JustMeErazem** [comment]
@condor2 I'm working on the website, but it would be beneficial to have some artwork (favicon, screenshots from the website etc.), so can you please send me an archive of the anarchylinux.org website?

**Comment by JustMeErazem** [comment]
@condor2 I've finished the website. I'm not 100% satisfied yet, but I think it's ready for release. I'll add the screenshots later (thanks for sending them) and tweak the design a bit more.

I'm not quite sure how to make this pull request though. The website source is on the [website-source](https://github.com/JustMeErazem/anarchy-linux/tree/website-source) branch and the website is deployed using a script to the [gh-pages](https://github.com/JustMeErazem/anarchy-linux/tree/gh-pages) branch.

I don't know how to make a pull request to a new branch through the Github interface, only how to push to a new branch. If you have any idea on how to do this, please let me know. And at the risk of sounding pushy, maybe you could add me as a collaborator, since even if I make pull requests for website updates, the deployment script would still need to be run manually (it doesn't work with pull requests).

In any case, feedback would be appreciated :)

**Comment by condor2** [comment]
I have added you as collaborator.

**Comment by JustMeErazem** [comment]
Thanks for adding me. I've pushed the two new branches, but you'll need to add the domain and enable the Github page from the gh-branch yourself.
