### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#821]
Add an issue/feature template to simplify and unify the submission process.

**Comment by JustMeErazem** [comment]
Apparently I can't create the issue template, only the ?owner? can.

**Comment by condor2** [comment]
Edit this how you like
https://github.com/deadhead420/anarchy-linux/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by JustMeErazem** [comment]
Ok, thanks

**Comment by JustMeErazem** [comment]
Fixed in #833.
