### ISSUE TITLE
Drop GUI installer

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#823]
I think the GUI installer should be completely dropped. Since there is currently no GUI release anyway, this wouldn't be that much of a problem for users. There are multiple reasons for dropping the support:

* Other projects have the GUI installer covered with more active development (eg. [EndeavourOS](https://endeavouros.com/))
* There are more bugs present in the GUI installer which makes development slower and more time exhaustive
* We have to support both versions, even though most people use the more known installers and people who want to customize their machines more use Anarchy (those same people are most likely happy with just the cli installer)

**To clarify, I'm talking about the installation process, not the final system (DEs should still be choosable in the cli installer)**

AFAIK @condor2, you're the only other person interested in maintaining Anarchy, so this is your choice.

**Comment by condor2** [comment]
Personally I do not like GUI installers and I used only CLI installer.

If not many people ask for Anarchy GUI then CLI is fine.

**Comment by JustMeErazem** [comment]
Yup, I'm exactly the same. Nobody has complained since you dropped the GUI releases, so there almost surely won't be a problem. Also there are a lot less variables to test with a cli installer so there should be less bugs. Is it okay then if I start removing the GUI installer from the code?

**Comment by trwnh** [comment]
I think GUI installer should be added back if/when GUI options are reintroduced

**Comment by JustMeErazem** [comment]
@trwnh What GUI options are you talking about? This Pull Request removed just the GUI installer, you can still use the cli version to install any DE or WM, just like before.

**Comment by trwnh** [comment]
What do you mean by "Since there is currently no GUI release anyway"?

**Comment by JustMeErazem** [comment]
At the time condor2 did not have the server capacity to upload the larger GUI release to users (we have since switched to uploading releases to Github). By that I meant that users weren't able to get the GUI installer anyway and that (as far as I know) nobody really complained about that. Thus I assumed that most people don't really care about Anarchy's GUI releases, since other projects already do them better (EndeavourOS and Manjaro for example).
