### ISSUE TITLE
Anarchy website's certificate is bad

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#828]
@condor2, it seems the website's certificate is set wrongly or something. Apparently it is pointing to a github domain (possibly something like deadhead420.github.io/anarchy-linux) instead of the anarchylinux.org domain.

Here's the Firefox screenshot:

![Screenshot from 2019-08-27 11-16-48](https://user-images.githubusercontent.com/46302511/63758521-2fa10780-c8bc-11e9-92dd-df5d351f9403.png)

**Comment by JustMeErazem** [comment]
Aha, the problem only occurs if prepending the website url with `www` [https://www.anarchylinux.org](https://www.anarchylinux.org/), but [https://anarchylinux.org/](https://anarchylinux.org/) works just fine.

You'll have to add both domains to GitHub (**anarchylinux.org** and **www.anarchylinux.org**).

**Comment by condor2** [comment]
I think will work now...

**Comment by JustMeErazem** [comment]
Yup, works.
