### ISSUE TITLE
Rename anarchy-creator.sh to e.g. build-iso.sh

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#838]
I propose that the anarchy-creator be renamed to something like "build-iso.sh", to make it clearer what it actually does, since anarchy-creator and anarchy-installer are very similar in naming, but very different in function.

Please voice your opinions.

Edit: Or we can move the anarchy-installer script into lib/ to make it clearer.

**Comment by condor2** [comment]
or iso-generator

**Comment by JustMeErazem** [comment]
I'll update it in the refactor branch
