### ISSUE TITLE
Redirect www.anarchylinux.org to anarchylinux.org

### ISSUE THREAD

**Issue by JustMeErazem** [deadhead420/anarchy-linux#843]
@condor2 Github only allows one domain in CNAME, so either people who use www.anarchylinux.org won't get a valid site, or people who use anarchylinux.org won't.

I've written that confusingly.
The point is that in the domain hosting www.anarchylinux.org should be forwarded to anarchylinux.org to help fix this.

I have no idea why it's like this, but here's the relevant link: https://help.github.com/en/articles/troubleshooting-custom-domains#github-repository-setup-errors

Currently Anarchy uses anarchylinux.org as its cname.

**Comment by condor2** [comment]
Work now.
This fking github doesn't have update files or settings from gh-pages.

**Comment by JustMeErazem** [comment]
@condor2 I'm just throwing this out there, but what if we moved Anarchy to a group account on Gitlab.

This way we could have separate repositores for the installer and website, later on possibly for even other ones, Gitlab pages is a lot simpler to deploy that Github pages and we could make use of Gitlab's CI scripts to test releases or even build them automatically to make sure they're reproducible.
