### ISSUE TITLE
1.0.5 iso not recognizing as UEFI

### ISSUE THREAD

**Issue by tymophy** [deadhead420/anarchy-linux#852]
Unable to boot a Anarchy USB on any machine I've tried via EFI w/ 1.0.5 iso.  Tested on Lenovo A485, Dell 7490, Dell 3379.  Does not see it as a UEFI compatible drive.  Wrote 1.0.4 image to same USB as 1.0.5 was written to, no issues booting.  Downloaded file matched sha256 sums.  Written with Etcher, etcher said written image verified correctly as well.

**Comment by condor2** [comment]
Redownload new 1.0.5 ISO an see if work now.

**Comment by tymophy** [comment]
It is indeed recognized as a UEFI compatible medium with the new 1.0.5 iso!!
