### ISSUE TITLE
openbox-themes (target not found) 

### ISSUE THREAD

**Issue by frpenguin** [deadhead420/anarchy-linux#857]
## Basic info:

**Anarchy version**: 1.0.5

**Installation method (VM/Host)**: VM (QEMU)

**System specifications (Processor, GPU, RAM ...)**: Ryzen 2700X

## What you expected would happen

Install anarchy with openbox

## What actually happened

The installer failed because it could not find the package 'openbox-themes'

## Steps needed to reproduce the bug

1. Start anarchy installer
2. Choose Anarchy-Advanced in Install System
2. In the Desktop Environment or Window Manager Section choose Anarchy-Openbox

## Extra info

![AnarchyLinux_Error](https://user-images.githubusercontent.com/53182405/65455848-c1b31600-de50-11e9-9276-af1ef39ac8c5.png)
## Possible fixes

openbox-themes is in the AUR

## Bug report checklist

* [x] I've checked for any existing issues similar to mine and tried the solutions provided there
* [x] I've checked online for any existing fixes to my issue and added the link above
* [x] I've tried taking logs and submitting them above

**Comment by erazemkokot** [comment]
We're currently working on being able to install packages from the AUR and the normal Arch repositories at the same time (since some packages might unexpectedly move to the AUR from the main repos - like openbox-themes), so this issue will hopefully be resolved soon, possibly even in 1.0.6.

**Comment by frpenguin** [comment]
Excelent! I presume you don't want me to post the issue again in the new repo. Can do if you want to.

**Comment by erazemkokot** [comment]
Actually please do, you'll save us some time ;)

**Comment by frpenguin** [comment]
Done! Closing This one as ith as now moved to new repo https://github.com/AnarchyLinux/anarchy/issues/1
