### ISSUE TITLE
More wayland desktop environments / window managers

### ISSUE THREAD

**Issue by rawsh** [deadhead420/anarchy-linux#90]
What I'm thinking of:

 * Sway (i3 fork with wayland)
 * Enlightenment
 * ~~Papyros Shell?~~ LiriOS

Love the installer!

**Comment by FredBezies** [comment]
Papyros is dead, merged into LiriOS : https://liri.io/blog/2017/01/25/lirios-0.9.0.html

**Comment by deadhead420** [comment]
I do plan on adding wayland support however it is not yet far along enough to add into the installer. For example the config file for weston "weston.ini" can vary greatly depending on the users configuration (hardware, etc), for this reason a default config would not work on all systems. Also wayland must be started manually by the user (or in .bashrc) and is not yet compatible (as far as I know) with any display manager. I think that Wayland + Weston still have a lot of work to be done before they will be ready for the average user. That day will come but for now it isn't very practical to include in the installer. If I can find a way to automatically generate weston.ini based on the users hardware configuration I will consider adding it, but until then we wait.

**Comment by notramo** [comment]
Sway is in a very early state. It is not ready for a newbie. If you can work in a Sway desktop, you can instal Arch without the Arch Anywhere Installer. I don't recommend adding Sway, and Weston, because there are many other things that we should work on.

**Comment by deadhead420** [comment]
Sway has been added. If its stable enough to be in the official repos they must be doing something right. I like to keep as many options possible in the installer so to appeal to advanced and beginner users alike.

**Comment by rawsh** [comment]
@deadhead420 great policy. I agree, sway seems stable to me. Thanks for your work on this installer!
